/* automatically generated from confirmation-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (confirmation_dialog_ui)
#endif
#ifdef __GNUC__
static const char confirmation_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char confirmation_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkDialog\" id=\"dialog1\"><prop"
  "erty name=\"can_focus\">False</property><property name=\"border_width\""
  ">5</property><property name=\"title\" translatable=\"yes\">Confirmation"
  "</property><property name=\"resizable\">False</property><property name="
  "\"modal\">True</property><property name=\"window_position\">center</pro"
  "perty><property name=\"icon_name\">dialog-question</property><property "
  "name=\"type_hint\">normal</property><child internal-child=\"vbox\"><obj"
  "ect class=\"GtkVBox\" id=\"dialog-vbox1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"spacing\">2</property><child internal-child=\"action_area\"><object"
  " class=\"GtkHButtonBox\" id=\"dialog-action_area1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"layout_style\">end</property><child><object class=\"GtkBu"
  "tton\" id=\"button2\"><property name=\"label\" translatable=\"yes\">Kee"
  "p this configuration</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"can_defa"
  "ult\">True</property><property name=\"has_default\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"use_act"
  "ion_appearance\">False</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"button1\"><property name=\"label\" translatable=\"yes\""
  ">Restore the previous configuration</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><property name=\"use_action_app"
  "earance\">False</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"pack_type\">end</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkHBox\" id=\"hbox1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><child><object class=\"GtkImage\" id=\"image1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"xalign\">0.20000000298023224</property><pr"
  "operty name=\"xpad\">10</property><property name=\"stock\">gtk-dialog-q"
  "uestion</property><property name=\"icon-size\">6</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkVBox\" id=\"vbox1\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><chil"
  "d><object class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"xalign\">0</property><property name=\"yalign\">0</property><proper"
  "ty name=\"ypad\">10</property><property name=\"label\" translatable=\"y"
  "es\">&lt;big&gt;&lt;b&gt;Would you like to keep this configuration?&lt;"
  "/b&gt;&lt;/big&gt;</property><property name=\"use_markup\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkLabel\" id=\"label2\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"xalign\">0</property><property name=\"yali"
  "gn\">0</property><property name=\"ypad\">10</property><property name=\""
  "label\" translatable=\"yes\">The previous configuration will be restore"
  "d in 10 seconds if you do not reply to this question.</property><proper"
  "ty name=\"wrap\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">1</property></packing></child></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild></object></child><action-widgets><action-widget response=\"2\">but"
  "ton2</action-widget><action-widget response=\"1\">button1</action-widge"
  "t></action-widgets></object></interface>"
};

static const unsigned confirmation_dialog_ui_length = 4443u;

