/* automatically generated from display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (display_dialog_ui)
#endif
#ifdef __GNUC__
static const char display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"XfceTitledDialog\" id=\"display-"
  "dialog\"><property name=\"can_focus\">False</property><property name=\""
  "title\" translatable=\"yes\">Display</property><property name=\"window_"
  "position\">center-on-parent</property><property name=\"default_width\">"
  "400</property><property name=\"default_height\">350</property><property"
  " name=\"icon_name\">video-display</property><property name=\"type_hint\""
  ">dialog</property><property name=\"subtitle\" translatable=\"yes\">Conf"
  "igure screen settings and layout</property><child internal-child=\"vbox"
  "\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"spacing\">2</property><child><object class=\"GtkVBox\" id=\""
  "plug-child\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"border_width\">12</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkHBox"
  "\" id=\"display-settings\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"spacing\">1"
  "2</property><child><object class=\"GtkAlignment\" id=\"randr-dnd\"><pro"
  "perty name=\"width_request\">300</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><child><plac"
  "eholder/></child></object><packing><property name=\"expand\">True</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkTable\" id=\"t"
  "able1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"n_rows\">8</property><property"
  " name=\"n_columns\">2</property><property name=\"column_spacing\">12</p"
  "roperty><property name=\"row_spacing\">6</property><child><object class"
  "=\"GtkComboBox\" id=\"randr-reflection\"><property name=\"can_focus\">F"
  "alse</property></object><packing><property name=\"left_attach\">1</prop"
  "erty><property name=\"right_attach\">2</property><property name=\"top_a"
  "ttach\">7</property><property name=\"bottom_attach\">8</property><prope"
  "rty name=\"y_options\">GTK_FILL</property></packing></child><child><obj"
  "ect class=\"GtkComboBox\" id=\"randr-rotation\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property></objec"
  "t><packing><property name=\"left_attach\">1</property><property name=\""
  "right_attach\">2</property><property name=\"top_attach\">6</property><p"
  "roperty name=\"bottom_attach\">7</property><property name=\"y_options\""
  ">GTK_FILL</property></packing></child><child><object class=\"GtkComboBo"
  "x\" id=\"randr-refresh-rate\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property></object><packing><proper"
  "ty name=\"left_attach\">1</property><property name=\"right_attach\">2</"
  "property><property name=\"top_attach\">5</property><property name=\"bot"
  "tom_attach\">6</property><property name=\"y_options\">GTK_FILL</propert"
  "y></packing></child><child><object class=\"GtkComboBox\" id=\"randr-res"
  "olution\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property></object><packing><property name=\"left_attac"
  "h\">1</property><property name=\"right_attach\">2</property><property n"
  "ame=\"top_attach\">4</property><property name=\"bottom_attach\">5</prop"
  "erty><property name=\"y_options\">GTK_FILL</property></packing></child>"
  "<child><object class=\"GtkLabel\" id=\"label-reflection\"><property nam"
  "e=\"can_focus\">False</property><property name=\"xalign\">0</property><"
  "property name=\"label\" translatable=\"yes\">Ref_lection:</property><pr"
  "operty name=\"use_underline\">True</property></object><packing><propert"
  "y name=\"top_attach\">7</property><property name=\"bottom_attach\">8</p"
  "roperty><property name=\"x_options\">GTK_FILL</property><property name="
  "\"y_options\">GTK_FILL</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"xalign\">0"
  "</property><property name=\"label\" translatable=\"yes\">Ro_tation:</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"top_attach\">6</property><property name=\"bottom_att"
  "ach\">7</property><property name=\"x_options\">GTK_FILL</property><prop"
  "erty name=\"y_options\">GTK_FILL</property></packing></child><child><ob"
  "ject class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">Refr"
  "esh _rate:</property><property name=\"use_underline\">True</property></"
  "object><packing><property name=\"top_attach\">5</property><property nam"
  "e=\"bottom_attach\">6</property><property name=\"x_options\">GTK_FILL</"
  "property><property name=\"y_options\">GTK_FILL</property></packing></ch"
  "ild><child><object class=\"GtkLabel\" id=\"label3\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"xalign\">0</property><property name=\"label\" translatabl"
  "e=\"yes\">R_esolution:</property><property name=\"use_underline\">True<"
  "/property></object><packing><property name=\"top_attach\">4</property><"
  "property name=\"bottom_attach\">5</property><property name=\"x_options\""
  ">GTK_FILL</property><property name=\"y_options\">GTK_FILL</property></p"
  "acking></child><child><object class=\"GtkCheckButton\" id=\"output-on\""
  "><property name=\"label\" translatable=\"yes\">_Use this display</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">False</property>"
  "<property name=\"use_underline\">True</property><property name=\"draw_i"
  "ndicator\">True</property></object><packing><property name=\"right_atta"
  "ch\">2</property><property name=\"top_attach\">1</property><property na"
  "me=\"bottom_attach\">2</property><property name=\"x_options\">GTK_FILL<"
  "/property><property name=\"y_options\">GTK_FILL</property></packing></c"
  "hild><child><object class=\"GtkCheckButton\" id=\"mirror-displays\"><pr"
  "operty name=\"label\" translatable=\"yes\">_Mirror displays</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"draw_indica"
  "tor\">True</property></object><packing><property name=\"right_attach\">"
  "2</property><property name=\"top_attach\">3</property><property name=\""
  "bottom_attach\">4</property><property name=\"x_options\">GTK_FILL</prop"
  "erty><property name=\"y_options\">GTK_FILL</property></packing></child>"
  "<child><object class=\"GtkComboBox\" id=\"randr-outputs\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty></object><packing><property name=\"right_attach\">2</property><prope"
  "rty name=\"y_options\">GTK_FILL</property></packing></child><child><obj"
  "ect class=\"GtkCheckButton\" id=\"primary\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Primary display</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">This is a hint for panels, docks and desktop to s"
  "how on this display preferably.</property><property name=\"use_underlin"
  "e\">True</property><property name=\"draw_indicator\">True</property></o"
  "bject><packing><property name=\"right_attach\">2</property><property na"
  "me=\"top_attach\">2</property><property name=\"bottom_attach\">3</prope"
  "rty><property name=\"x_options\">GTK_FILL</property><property name=\"y_"
  "options\">GTK_FILL</property></packing></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">0</property></packing></c"
  "hild><child><object class=\"GtkAlignment\" id=\"alignment1\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><child><object class=\"GtkHBox\" id=\"hbox1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><ch"
  "ild><object class=\"GtkCheckButton\" id=\"minimal-autoshow\"><property "
  "name=\"label\" translatable=\"yes\">Configure _new displays when connec"
  "ted</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkHButtonBox\" id=\"hbuttonbox1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "spacing\">6</property><property name=\"layout_style\">end</property><ch"
  "ild><object class=\"GtkToggleButton\" id=\"identify-displays\"><propert"
  "y name=\"label\" translatable=\"yes\">Identify Displays</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"pack_type\">end</property><property"
  " name=\"position\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"apply\"><property name=\"label\">gtk-apply</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">True</property><prope"
  "rty name=\"use_stock\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"pack_type\">end</property><property name=\"position\">1</p"
  "roperty></packing></child></object><packing><property name=\"expand\">T"
  "rue</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">1</property></packing></child></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">F"
  "alse</property><property name=\"position\">1</property></packing></chil"
  "d></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">0</property></"
  "packing></child><child internal-child=\"action_area\"><object class=\"G"
  "tkHButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"layout_style\">end</property><child><object class=\"GtkButton\" id="
  "\"button-help\"><property name=\"label\">gtk-help</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"receives_default\">True</property><property name=\""
  "use_stock\">True</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property><property name=\"secondary\">True</property></"
  "packing></child><child><object class=\"GtkButton\" id=\"button-close\">"
  "<property name=\"label\">gtk-close</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><property name=\"use_stock\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">1"
  "</property></packing></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"pack_type\">end</property><property name=\"position\">1</property></p"
  "acking></child></object></child><action-widgets><action-widget response"
  "=\"-11\">button-help</action-widget><action-widget response=\"0\">butto"
  "n-close</action-widget></action-widgets></object></interface>"
};

static const unsigned display_dialog_ui_length = 11585u;

