/* automatically generated from minimal-display-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (minimal_display_dialog_ui)
#endif
#ifdef __GNUC__
static const char minimal_display_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char minimal_display_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkWindow\" id=\"dialog\"><prope"
  "rty name=\"can_focus\">False</property><property name=\"title\" transla"
  "table=\"yes\">Displays</property><property name=\"resizable\">False</pr"
  "operty><property name=\"window_position\">center</property><property na"
  "me=\"icon_name\">video-display</property><property name=\"type_hint\">d"
  "ialog</property><child><object class=\"GtkVBox\" id=\"vbox1\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"border_width\">6</property><property name=\"spa"
  "cing\">6</property><child><object class=\"GtkTable\" id=\"buttons\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"n_rows\">2</property><property name=\"n_c"
  "olumns\">4</property><property name=\"column_spacing\">24</property><pr"
  "operty name=\"row_spacing\">3</property><child><object class=\"GtkLabel"
  "\" id=\"label1\"><property name=\"width_request\">128</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"label\" translatable=\"yes\">Only Display 1</"
  "property><property name=\"ellipsize\">middle</property></object><packin"
  "g><property name=\"top_attach\">1</property><property name=\"bottom_att"
  "ach\">2</property><property name=\"x_options\">GTK_FILL</property><prop"
  "erty name=\"y_options\">GTK_FILL</property></packing></child><child><ob"
  "ject class=\"GtkLabel\" id=\"label2\"><property name=\"width_request\">"
  "128</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"tooltip_text\" translata"
  "ble=\"yes\">Mirror Displays</property><property name=\"label\" translat"
  "able=\"yes\">Mirror Displays</property><property name=\"ellipsize\">mid"
  "dle</property></object><packing><property name=\"left_attach\">1</prope"
  "rty><property name=\"right_attach\">2</property><property name=\"top_at"
  "tach\">1</property><property name=\"bottom_attach\">2</property><proper"
  "ty name=\"x_options\">GTK_FILL</property><property name=\"y_options\">G"
  "TK_FILL</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label3\"><property name=\"width_request\">128</property><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"tooltip_text\" translatable=\"yes\">Extend to the"
  " right</property><property name=\"label\" translatable=\"yes\">Extend t"
  "o the right</property><property name=\"ellipsize\">middle</property></o"
  "bject><packing><property name=\"left_attach\">2</property><property nam"
  "e=\"right_attach\">3</property><property name=\"top_attach\">1</propert"
  "y><property name=\"bottom_attach\">2</property><property name=\"x_optio"
  "ns\">GTK_FILL</property><property name=\"y_options\">GTK_FILL</property"
  "></packing></child><child><object class=\"GtkLabel\" id=\"label4\"><pro"
  "perty name=\"width_request\">128</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">Only Display 2</property><property na"
  "me=\"ellipsize\">middle</property></object><packing><property name=\"le"
  "ft_attach\">3</property><property name=\"right_attach\">4</property><pr"
  "operty name=\"top_attach\">1</property><property name=\"bottom_attach\""
  ">2</property><property name=\"x_options\">GTK_FILL</property><property "
  "name=\"y_options\">GTK_FILL</property></packing></child><child><object "
  "class=\"GtkRadioButton\" id=\"display1\"><property name=\"width_request"
  "\">128</property><property name=\"height_request\">128</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"draw_in"
  "dicator\">False</property><child><object class=\"GtkImage\" id=\"image1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property></object></child></object><packing><property name=\""
  "x_options\"/><property name=\"y_options\"/></packing></child><child><ob"
  "ject class=\"GtkRadioButton\" id=\"mirror\"><property name=\"width_requ"
  "est\">128</property><property name=\"height_request\">128</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"acti"
  "ve\">True</property><property name=\"draw_indicator\">False</property><"
  "property name=\"group\">display1</property><child><object class=\"GtkIm"
  "age\" id=\"image2\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property></object></child></object><packing>"
  "<property name=\"left_attach\">1</property><property name=\"right_attac"
  "h\">2</property><property name=\"x_options\"/><property name=\"y_option"
  "s\"/></packing></child><child><object class=\"GtkRadioButton\" id=\"ext"
  "end_right\"><property name=\"width_request\">128</property><property na"
  "me=\"height_request\">128</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"active\">True</property><property nam"
  "e=\"draw_indicator\">False</property><property name=\"group\">display1<"
  "/property><child><object class=\"GtkImage\" id=\"image3\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty></object></child></object><packing><property name=\"left_attach\">2<"
  "/property><property name=\"right_attach\">3</property><property name=\""
  "x_options\"/><property name=\"y_options\"/></packing></child><child><ob"
  "ject class=\"GtkRadioButton\" id=\"display2\"><property name=\"width_re"
  "quest\">128</property><property name=\"height_request\">128</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"ac"
  "tive\">True</property><property name=\"draw_indicator\">False</property"
  "><property name=\"group\">display1</property><child><object class=\"Gtk"
  "Image\" id=\"image4\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property></object></child></object><packin"
  "g><property name=\"left_attach\">3</property><property name=\"right_att"
  "ach\">4</property><property name=\"x_options\"/><property name=\"y_opti"
  "ons\"/></packing></child></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkHButto"
  "nBox\" id=\"hbuttonbox1\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><child><object class=\"GtkBut"
  "ton\" id=\"advanced_button\"><property name=\"label\" translatable=\"ye"
  "s\">Advanced</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">True</property><property name=\"use_action_appearance\">False</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">0</propert"
  "y></packing></child><child><object class=\"GtkRadioButton\" id=\"fake_b"
  "utton\"><property name=\"label\" translatable=\"yes\">radiobutton</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_action_appearance\">"
  "False</property><property name=\"active\">True</property><property name"
  "=\"draw_indicator\">True</property><property name=\"group\">display1</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">1</pro"
  "perty></packing></child><child><object class=\"GtkButton\" id=\"cancel_"
  "button\"><property name=\"label\">gtk-close</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"use_stock\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">2</pro"
  "perty></packing></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"pa"
  "ck_type\">end</property><property name=\"position\">1</property></packi"
  "ng></child></object></child></object></interface>"
};

static const unsigned minimal_display_dialog_ui_length = 8235u;

