/* automatically generated from accessibility-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (accessibility_dialog_ui)
#endif
#ifdef __GNUC__
static const char accessibility_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char accessibility_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"GtkAdjustment\" id=\"bounce-keys"
  "-delay\"><property name=\"lower\">50</property><property name=\"upper\""
  ">1000</property><property name=\"value\">500</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"mouse-emulation-curv"
  "e\"><property name=\"lower\">-1000</property><property name=\"upper\">1"
  "000</property><property name=\"step_increment\">10</property><property "
  "name=\"page_increment\">100</property></object><object class=\"GtkAdjus"
  "tment\" id=\"mouse-emulation-delay\"><property name=\"lower\">1</proper"
  "ty><property name=\"upper\">1000</property><property name=\"value\">150"
  "</property><property name=\"step_increment\">10</property><property nam"
  "e=\"page_increment\">100</property></object><object class=\"GtkAdjustme"
  "nt\" id=\"mouse-emulation-interval\"><property name=\"lower\">10</prope"
  "rty><property name=\"upper\">1000</property><property name=\"value\">20"
  "</property><property name=\"step_increment\">1</property><property name"
  "=\"page_increment\">10</property></object><object class=\"GtkAdjustment"
  "\" id=\"mouse-emulation-max-speed\"><property name=\"lower\">1</propert"
  "y><property name=\"upper\">2000</property><property name=\"value\">1000"
  "</property><property name=\"step_increment\">10</property><property nam"
  "e=\"page_increment\">100</property></object><object class=\"GtkAdjustme"
  "nt\" id=\"mouse-emulation-time-to-max\"><property name=\"lower\">100</p"
  "roperty><property name=\"upper\">10000</property><property name=\"value"
  "\">3000</property><property name=\"step_increment\">10</property><prope"
  "rty name=\"page_increment\">100</property></object><object class=\"GtkA"
  "djustment\" id=\"slow-keys-delay\"><property name=\"lower\">50</propert"
  "y><property name=\"upper\">1000</property><property name=\"value\">500<"
  "/property><property name=\"step_increment\">10</property><property name"
  "=\"page_increment\">100</property></object><object class=\"XfceTitledDi"
  "alog\" id=\"dialog\"><property name=\"can_focus\">False</property><prop"
  "erty name=\"title\" translatable=\"yes\">Accessibility</property><prope"
  "rty name=\"window_position\">center-on-parent</property><property name="
  "\"icon_name\">preferences-desktop-accessibility</property><property nam"
  "e=\"type_hint\">dialog</property><property name=\"subtitle\" translatab"
  "le=\"yes\">Configure keyboard and mouse accessibility</property><child "
  "internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox1\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"spacing\">2</property><child internal-c"
  "hild=\"action_area\"><object class=\"GtkHButtonBox\" id=\"dialog-action"
  "_area1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"layout_style\">end</property>"
  "<child><object class=\"GtkButton\" id=\"button2\"><property name=\"labe"
  "l\">gtk-close</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">True</prop"
  "erty><property name=\"use_stock\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">gt"
  "k-help</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">True</property><p"
  "roperty name=\"use_stock\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">0</property><property name=\"secondary\">Tr"
  "ue</property></packing></child></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">True</property><property na"
  "me=\"pack_type\">end</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkVBox\" id=\"plug-child\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><child><object class=\"GtkNotebook\" id=\"notebook1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"border_width\">6</property><child><object "
  "class=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">6</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkCheckButton\" id=\"start-at\"><property name=\"label\" tr"
  "anslatable=\"yes\">_Enable assistive technologies</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">If enabled, the session manager will start the re"
  "quired applications for screen readers and magnifiers</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"draw_indicato"
  "r\">True</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkAlignment\""
  " id=\"alignment5\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><child><placeholder/></child></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child><child><object class=\"GtkHBox\" id=\"info-logout\"><property na"
  "me=\"can_focus\">False</property><property name=\"spacing\">12</propert"
  "y><child><object class=\"GtkImage\" id=\"image1\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"stock\">gtk-info</property><property name=\"icon-size\">5</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkLabel\" id=\"label18\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">Assistive technologies will be available t"
  "he\nnext time you login</property><property name=\"wrap\">True</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">2</property></packing></child><child><object class=\"GtkHBox\" id=\"in"
  "fo-no-at\"><property name=\"can_focus\">False</property><property name="
  "\"spacing\">12</property><child><object class=\"GtkImage\" id=\"image2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"stock\">gtk-dialog-warning</property>"
  "<property name=\"icon-size\">5</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkLabel\" id=\"label20\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"xali"
  "gn\">0</property><property name=\"label\" translatable=\"yes\">No AT-SP"
  "I provider was found on your system</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">3</property></packing></chi"
  "ld></object></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label17\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">Assistive _Technologies</property><property name=\"use_underline\">Tru"
  "e</property></object><packing><property name=\"position\">2</property><"
  "property name=\"tab_fill\">False</property></packing></child><child><ob"
  "ject class=\"GtkVBox\" id=\"vbox2\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"bo"
  "rder_width\">12</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label_xalign\">0</property><property name=\"shadow_type\">none</pro"
  "perty><child><object class=\"GtkAlignment\" id=\"alignment1\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"bottom_padding\">6</property><property name=\"l"
  "eft_padding\">12</property><child><object class=\"GtkVBox\" id=\"vbox3\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkCheckButton\" id"
  "=\"sticky-keys-enabled\"><property name=\"label\" translatable=\"yes\">"
  "_Use sticky keys</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"tooltip_text\" translatable=\"yes\">When selec"
  "ted, modifier keys (such as Control, Alt, and Shift) do not need to be "
  "held down (they can be pressed and then released) when multiple keys wo"
  "uld normally need to be pressed at the same time</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkAlignment\" id="
  "\"sticky-keys-box\"><property name=\"visible\">True</property><property"
  " name=\"sensitive\">False</property><property name=\"can_focus\">False<"
  "/property><property name=\"left_padding\">18</property><child><object c"
  "lass=\"GtkVBox\" id=\"vbox7\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkCheckButton\" id=\"sticky-keys-l"
  "atch-to-lock\"><property name=\"label\" translatable=\"yes\">_Lock stic"
  "ky keys</property><property name=\"use_action_appearance\">False</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">False</property>"
  "<property name=\"tooltip_text\" translatable=\"yes\">When selected, mod"
  "ifier keys (such as Control, Alt, and Shift) will remain locked in the "
  "pressed state until pressed again</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkCheckButton\" id=\"sticky-keys-t"
  "wo-keys-disable\"><property name=\"label\" translatable=\"yes\">Disable"
  " sticky keys if two keys are _pressed</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"tooltip_text\" translata"
  "ble=\"yes\">When selected, the \"sticky keys\" feature will be disabled"
  " if two keys are pressed simultaneously</property><property name=\"use_"
  "underline\">True</property><property name=\"xalign\">0</property><prope"
  "rty name=\"yalign\">0</property><property name=\"draw_indicator\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">1</p"
  "roperty></packing></child></object></child></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object></chi"
  "ld></object></child><child type=\"label\"><object class=\"GtkLabel\" id"
  "=\"label3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Sticky Keys</property><attributes><attribute name=\"weight\" value=\""
  "bold\"/></attributes></object></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkFrame\" id=\"frame2\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label_x"
  "align\">0</property><property name=\"shadow_type\">none</property><chil"
  "d><object class=\"GtkAlignment\" id=\"alignment2\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"bottom_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkVBox\" id=\"vbox4\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"border_width\">6</property><property name=\"spa"
  "cing\">6</property><child><object class=\"GtkCheckButton\" id=\"slow-ke"
  "ys-enabled\"><property name=\"label\" translatable=\"yes\">Use slow _ke"
  "ys</property><property name=\"use_action_appearance\">False</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"tooltip_text\" translatable=\"yes\">To help prevent acciden"
  "tal keystrokes, slow keys requires that a key is held for a certain min"
  "imum amount of time before the keystroke will be accepted</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"draw_indi"
  "cator\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkAlignm"
  "ent\" id=\"slow-keys-box\"><property name=\"visible\">True</property><p"
  "roperty name=\"sensitive\">False</property><property name=\"can_focus\""
  ">False</property><property name=\"left_padding\">18</property><child><o"
  "bject class=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"s"
  "pacing\">12</property><child><object class=\"GtkLabel\" id=\"label6\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"xalign\">0</property><property name=\"l"
  "abel\" translatable=\"yes\">Acceptance _delay:</property><property name"
  "=\"use_underline\">True</property><property name=\"mnemonic_widget\">sl"
  "ow-keys-scale</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkHScal"
  "e\" id=\"slow-keys-scale\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">True</property><property name=\"tooltip_text"
  "\" translatable=\"yes\">The amount of time, in milliseconds, that must "
  "elapse before a keystroke will be accepted</property><property name=\"a"
  "djustment\">slow-keys-delay</property><property name=\"digits\">0</prop"
  "erty><property name=\"value_pos\">right</property></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t></child></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label\" translatable=\"yes\">Slow Keys</property><attributes"
  "><attribute name=\"weight\" value=\"bold\"/></attributes></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkFrame\" id=\"frame3\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label_xalign\">0</property><property name="
  "\"shadow_type\">none</property><child><object class=\"GtkAlignment\" id"
  "=\"alignment3\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkVBox\" id=\"vbox6\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"border_width\">6</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkCheckButton\" id=\"bounce-keys-enabl"
  "ed\"><property name=\"label\" translatable=\"yes\">Use _bounce keys</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">To help prevent accidental mu"
  "ltiple keystrokes, bounce keys imposes a minimum delay between keystrok"
  "es</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkAlignment\" id=\"bounce-keys-box\"><property name=\"visible\""
  ">True</property><property name=\"sensitive\">False</property><property "
  "name=\"can_focus\">False</property><property name=\"left_padding\">18</"
  "property><child><object class=\"GtkHBox\" id=\"hbox2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label9\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"xalign\">0</property><p"
  "roperty name=\"label\" translatable=\"yes\">K_eystroke delay:</property"
  "><property name=\"use_underline\">True</property><property name=\"mnemo"
  "nic_widget\">bounce-keys-scale</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkHScale\" id=\"bounce-keys-scale\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">The amount of time, in millis"
  "econds, required between keystrokes</property><property name=\"adjustme"
  "nt\">bounce-keys-delay</property><property name=\"digits\">0</property>"
  "<property name=\"value_pos\">right</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child></object></c"
  "hild></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child></object></child></object></child><child type=\"labe"
  "l\"><object class=\"GtkLabel\" id=\"label5\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Bounce Keys</property><attributes><"
  "attribute name=\"weight\" value=\"bold\"/></attributes></object></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">2</property></"
  "packing></child></object><packing><property name=\"position\">1</proper"
  "ty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id="
  "\"label1\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">Keyboa_rd</property><property name=\"use_underline\">True</property></"
  "object><packing><property name=\"position\">1</property><property name="
  "\"tab_fill\">False</property></packing></child><child><object class=\"G"
  "tkVBox\" id=\"vbox5\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"border_width\">1"
  "2</property><child><object class=\"GtkFrame\" id=\"frame4\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label_xalign\">0</property><property name=\"shado"
  "w_type\">none</property><child><object class=\"GtkAlignment\" id=\"alig"
  "nment4\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"border_width\">6</property><p"
  "roperty name=\"left_padding\">12</property><child><object class=\"GtkVB"
  "ox\" id=\"vbox8\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"spacing\">6</propert"
  "y><child><object class=\"GtkCheckButton\" id=\"mouse-emulation-enabled\""
  "><property name=\"label\" translatable=\"yes\">_Use mouse emulation</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">When selected, the mouse poin"
  "ter can be controlled using the keyboard number pad</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkAlignment\" id"
  "=\"mouse-emulation-box\"><property name=\"visible\">True</property><pro"
  "perty name=\"sensitive\">False</property><property name=\"can_focus\">F"
  "alse</property><property name=\"left_padding\">18</property><child><obj"
  "ect class=\"GtkTable\" id=\"table1\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"n"
  "_rows\">5</property><property name=\"n_columns\">3</property><property "
  "name=\"column_spacing\">12</property><property name=\"row_spacing\">6</"
  "property><child><object class=\"GtkLabel\" id=\"label16\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"xalign\">0</property><property name=\"label\" trans"
  "latable=\"yes\">R_epeat interval:</property><property name=\"use_underl"
  "ine\">True</property><property name=\"mnemonic_widget\">interval-widget"
  "</property></object><packing><property name=\"top_attach\">1</property>"
  "<property name=\"bottom_attach\">2</property><property name=\"x_options"
  "\">GTK_FILL</property></packing></child><child><object class=\"GtkLabel"
  "\" id=\"label7\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"xalign\">0</property>"
  "<property name=\"label\" translatable=\"yes\">_Acceleration delay:</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">delay-widget</property></object><packing><property na"
  "me=\"x_options\">GTK_FILL</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"label19\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"xalign"
  "\">0</property><property name=\"label\" translatable=\"yes\">Accelerati"
  "on t_ime:</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"mnemonic_widget\">ttm-widget</property></object><packing>"
  "<property name=\"top_attach\">2</property><property name=\"bottom_attac"
  "h\">3</property><property name=\"x_options\">GTK_FILL</property></packi"
  "ng></child><child><object class=\"GtkLabel\" id=\"label22\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"xalign\">0</property><property name=\"label\" tra"
  "nslatable=\"yes\">Ma_ximum speed:</property><property name=\"use_underl"
  "ine\">True</property><property name=\"mnemonic_widget\">max-speed-widge"
  "t</property></object><packing><property name=\"top_attach\">3</property"
  "><property name=\"bottom_attach\">4</property><property name=\"x_option"
  "s\">GTK_FILL</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label8\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"xalign\">0</property"
  "><property name=\"label\" translatable=\"yes\">Acceleration _profile:</"
  "property><property name=\"use_underline\">True</property><property name"
  "=\"mnemonic_widget\">curve-widget</property></object><packing><property"
  " name=\"top_attach\">4</property><property name=\"bottom_attach\">5</pr"
  "operty><property name=\"x_options\">GTK_FILL</property></packing></chil"
  "d><child><object class=\"GtkLabel\" id=\"label10\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"xalign\">0</property><property name=\"label\" translatable"
  "=\"yes\">msec</property></object><packing><property name=\"left_attach\""
  ">2</property><property name=\"right_attach\">3</property></packing></ch"
  "ild><child><object class=\"GtkLabel\" id=\"label11\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"xalign\">0</property><property name=\"label\" translatab"
  "le=\"yes\">msec</property></object><packing><property name=\"left_attac"
  "h\">2</property><property name=\"right_attach\">3</property><property n"
  "ame=\"top_attach\">1</property><property name=\"bottom_attach\">2</prop"
  "erty></packing></child><child><object class=\"GtkLabel\" id=\"label13\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">msec</property></object><packing><property"
  " name=\"left_attach\">2</property><property name=\"right_attach\">3</pr"
  "operty><property name=\"top_attach\">2</property><property name=\"botto"
  "m_attach\">3</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label14\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"xalign\">0</propert"
  "y></object><packing><property name=\"left_attach\">2</property><propert"
  "y name=\"right_attach\">3</property><property name=\"top_attach\">4</pr"
  "operty><property name=\"bottom_attach\">5</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"label15\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"xalign\">0</property><property name=\"label\" translatable=\""
  "yes\">pixels/sec</property></object><packing><property name=\"left_atta"
  "ch\">2</property><property name=\"right_attach\">3</property><property "
  "name=\"top_attach\">3</property><property name=\"bottom_attach\">4</pro"
  "perty></packing></child><child><object class=\"GtkSpinButton\" id=\"del"
  "ay-widget\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">The time, in milliseconds, between the initial key press and f"
  "irst repeated motion event</property><property name=\"primary_icon_acti"
  "vatable\">False</property><property name=\"secondary_icon_activatable\""
  ">False</property><property name=\"primary_icon_sensitive\">True</proper"
  "ty><property name=\"secondary_icon_sensitive\">True</property><property"
  " name=\"adjustment\">mouse-emulation-delay</property><property name=\"n"
  "umeric\">True</property><property name=\"update_policy\">if-valid</prop"
  "erty></object><packing><property name=\"left_attach\">1</property><prop"
  "erty name=\"right_attach\">2</property><property name=\"x_options\">GTK"
  "_FILL</property></packing></child><child><object class=\"GtkSpinButton\""
  " id=\"interval-widget\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"tooltip_text\" "
  "translatable=\"yes\">The time, in milliseconds, between repeated motion"
  " events</property><property name=\"primary_icon_activatable\">False</pr"
  "operty><property name=\"secondary_icon_activatable\">False</property><p"
  "roperty name=\"primary_icon_sensitive\">True</property><property name=\""
  "secondary_icon_sensitive\">True</property><property name=\"adjustment\""
  ">mouse-emulation-interval</property><property name=\"numeric\">True</pr"
  "operty><property name=\"update_policy\">if-valid</property></object><pa"
  "cking><property name=\"left_attach\">1</property><property name=\"right"
  "_attach\">2</property><property name=\"top_attach\">1</property><proper"
  "ty name=\"bottom_attach\">2</property><property name=\"x_options\">GTK_"
  "FILL</property></packing></child><child><object class=\"GtkSpinButton\""
  " id=\"curve-widget\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"tooltip_text\" tra"
  "nslatable=\"yes\">The ramp used to reach maximum pointer speed</propert"
  "y><property name=\"primary_icon_activatable\">False</property><property"
  " name=\"secondary_icon_activatable\">False</property><property name=\"p"
  "rimary_icon_sensitive\">True</property><property name=\"secondary_icon_"
  "sensitive\">True</property><property name=\"adjustment\">mouse-emulatio"
  "n-curve</property><property name=\"numeric\">True</property><property n"
  "ame=\"update_policy\">if-valid</property></object><packing><property na"
  "me=\"left_attach\">1</property><property name=\"right_attach\">2</prope"
  "rty><property name=\"top_attach\">4</property><property name=\"bottom_a"
  "ttach\">5</property><property name=\"x_options\">GTK_FILL</property></p"
  "acking></child><child><object class=\"GtkSpinButton\" id=\"max-speed-wi"
  "dget\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">The maximum pointer speed after acceleration</property><property na"
  "me=\"primary_icon_activatable\">False</property><property name=\"second"
  "ary_icon_activatable\">False</property><property name=\"primary_icon_se"
  "nsitive\">True</property><property name=\"secondary_icon_sensitive\">Tr"
  "ue</property><property name=\"adjustment\">mouse-emulation-max-speed</p"
  "roperty><property name=\"numeric\">True</property><property name=\"upda"
  "te_policy\">if-valid</property></object><packing><property name=\"left_"
  "attach\">1</property><property name=\"right_attach\">2</property><prope"
  "rty name=\"top_attach\">3</property><property name=\"bottom_attach\">4<"
  "/property><property name=\"x_options\">GTK_FILL</property></packing></c"
  "hild><child><object class=\"GtkSpinButton\" id=\"ttm-widget\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"tooltip_text\" translatable=\"yes\">The time, in"
  " milliseconds, to get to maximum speed</property><property name=\"prima"
  "ry_icon_activatable\">False</property><property name=\"secondary_icon_a"
  "ctivatable\">False</property><property name=\"primary_icon_sensitive\">"
  "True</property><property name=\"secondary_icon_sensitive\">True</proper"
  "ty><property name=\"adjustment\">mouse-emulation-time-to-max</property>"
  "<property name=\"numeric\">True</property><property name=\"update_polic"
  "y\">if-valid</property></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"right_attach\">2</property><property name"
  "=\"top_attach\">2</property><property name=\"bottom_attach\">3</propert"
  "y><property name=\"x_options\">GTK_FILL</property></packing></child></o"
  "bject></child></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">1<"
  "/property></packing></child></object></child></object></child><child ty"
  "pe=\"label\"><object class=\"GtkLabel\" id=\"label12\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Mouse Emulation</property>"
  "<attributes><attribute name=\"weight\" value=\"bold\"/></attributes></o"
  "bject></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">0"
  "</property></packing></child></object><packing><property name=\"positio"
  "n\">2</property></packing></child><child type=\"tab\"><object class=\"G"
  "tkLabel\" id=\"label2\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">_Mouse</property><property name=\"use_underline\">True</"
  "property></object><packing><property name=\"position\">2</property><pro"
  "perty name=\"tab_fill\">False</property></packing></child></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">1</property></p"
  "acking></child></object></child><action-widgets><action-widget response"
  "=\"0\">button2</action-widget><action-widget response=\"-11\">button1</"
  "action-widget></action-widgets></object></interface>"
};

static const unsigned accessibility_dialog_ui_length = 31932u;

