/* automatically generated from keyboard-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (keyboard_dialog_ui)
#endif
#ifdef __GNUC__
static const char keyboard_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char keyboard_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"GtkImage\" id=\"image1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"stock\">gtk-revert-to-saved</property></objec"
  "t><object class=\"GtkImage\" id=\"image2\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"stock\">gtk-revert-to-saved</property></object><object class=\"Xfc"
  "eTitledDialog\" id=\"keyboard-layout-selection-dialog\"><property name="
  "\"can_focus\">False</property><property name=\"title\" translatable=\"y"
  "es\">Keyboard layout selection</property><property name=\"window_positi"
  "on\">center-on-parent</property><property name=\"default_height\">300</"
  "property><property name=\"icon_name\">preferences-desktop-keyboard</pro"
  "perty><property name=\"type_hint\">dialog</property><property name=\"su"
  "btitle\" translatable=\"yes\">Select keyboard layout and variant</prope"
  "rty><child internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"dialo"
  "g-vbox2\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"spacing\">2</property><child"
  " internal-child=\"action_area\"><object class=\"GtkHButtonBox\" id=\"di"
  "alog-action_area2\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"layout_style\">end"
  "</property><child><object class=\"GtkButton\" id=\"layout_selection_ok_"
  "button\"><property name=\"label\">gtk-ok</property><property name=\"use"
  "_action_appearance\">False</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"use_stock\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkButton\" id=\"layout_sel"
  "ection_cancel_button\"><property name=\"label\">gtk-cancel</property><p"
  "roperty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"use_s"
  "tock\">True</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"pack_type\">end</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkScrolledWindow\" id="
  "\"scrolledwindow3\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"border_width\">6</p"
  "roperty><property name=\"hscrollbar_policy\">automatic</property><prope"
  "rty name=\"vscrollbar_policy\">automatic</property><property name=\"sha"
  "dow_type\">in</property><child><object class=\"GtkTreeView\" id=\"layou"
  "t_selection_view\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"headers_visible\">Fa"
  "lse</property><property name=\"search_column\">0</property></object></c"
  "hild></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child></object></child><action-widgets><action-widget resp"
  "onse=\"-5\">layout_selection_ok_button</action-widget><action-widget re"
  "sponse=\"-6\">layout_selection_cancel_button</action-widget></action-wi"
  "dgets></object><object class=\"XfceTitledDialog\" id=\"keyboard-setting"
  "s-dialog\"><property name=\"can_focus\">False</property><property name="
  "\"title\" translatable=\"yes\">Keyboard</property><property name=\"wind"
  "ow_position\">center-on-parent</property><property name=\"default_width"
  "\">400</property><property name=\"icon_name\">preferences-desktop-keybo"
  "ard</property><property name=\"type_hint\">dialog</property><property n"
  "ame=\"subtitle\" translatable=\"yes\">Edit keyboard settings and applic"
  "ation shortcuts</property><child internal-child=\"vbox\"><object class="
  "\"GtkVBox\" id=\"dialog-vbox1\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"spacin"
  "g\">2</property><child internal-child=\"action_area\"><object class=\"G"
  "tkHButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"layout_style\">end</property><child><object class=\"GtkButton\" id="
  "\"button1\"><property name=\"label\">gtk-help</property><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">True</property><property name=\"use_stock\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">0</p"
  "roperty><property name=\"secondary\">True</property></packing></child><"
  "child><object class=\"GtkButton\" id=\"button2\"><property name=\"label"
  "\">gtk-close</property><property name=\"use_action_appearance\">False</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">True</prope"
  "rty><property name=\"use_stock\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">0</property></packing></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"pack_type\">end</property><proper"
  "ty name=\"position\">0</property></packing></child><child><object class"
  "=\"GtkVBox\" id=\"plug-child\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">6</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkNotebook\" id=\"notebook1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><child><object"
  " class=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"border"
  "_width\">12</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment5\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"top_padding\">6</property><property name=\"bottom_p"
  "adding\">6</property><property name=\"left_padding\">18</property><prop"
  "erty name=\"right_padding\">6</property><child><object class=\"GtkCheck"
  "Button\" id=\"restore_numlock\"><property name=\"label\" translatable=\""
  "yes\">Restore num l_ock state on startup</property><property name=\"use"
  "_action_appearance\">False</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">False</property><property name=\"use_underline\">True<"
  "/property><property name=\"draw_indicator\">True</property></object></c"
  "hild></object></child><child type=\"label\"><object class=\"GtkLabel\" "
  "id=\"label9\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">General</property><property name=\"use_markup\">True</property><at"
  "tributes><attribute name=\"weight\" value=\"bold\"/></attributes></obje"
  "ct></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkFrame\" id=\"frame2"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label_xalign\">0</property><propert"
  "y name=\"shadow_type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment2\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"left_padding\">"
  "12</property><child><object class=\"GtkVBox\" id=\"vbox1\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"border_width\">6</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkCheckButton\" id=\"xkb_key_re"
  "peat_check\"><property name=\"label\" translatable=\"yes\">_Enable key "
  "repeat</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"tooltip_text\" translatable=\"yes\">When selected, pres"
  "sing and holding down a key emits the same character over and over agai"
  "n</property><property name=\"use_underline\">True</property><property n"
  "ame=\"active\">True</property><property name=\"draw_indicator\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">0</pro"
  "perty></packing></child><child><object class=\"GtkAlignment\" id=\"xkb_"
  "key_repeat_box\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"left_padding\">18</pr"
  "operty><child><object class=\"GtkVBox\" id=\"vbox6\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkLabel\" "
  "id=\"label7\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"xalign\">0</property><pr"
  "operty name=\"label\" translatable=\"yes\">_Repeat delay:</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"mnemonic_"
  "widget\">xkb_key_repeat_delay_scale</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkHScale\" id=\"xkb_key_repeat_delay_scale\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"tooltip_text\" translatable=\"yes\">The time, in m"
  "illiseconds, before a pressed key begins repeating</property><property "
  "name=\"update_policy\">delayed</property><property name=\"adjustment\">"
  "xkb_key_repeat_delay</property><property name=\"digits\">0</property><p"
  "roperty name=\"value_pos\">right</property></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child><child><object"
  " class=\"GtkLabel\" id=\"label10\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"xal"
  "ign\">0</property><property name=\"label\" translatable=\"yes\">Repe_at"
  " speed:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">xkb_key_repeat_rate_scale</property></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">2</property></packin"
  "g></child><child><object class=\"GtkHScale\" id=\"xkb_key_repeat_rate_s"
  "cale\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">The rate at which keystrokes are generated while a key is pressed</"
  "property><property name=\"update_policy\">delayed</property><property n"
  "ame=\"adjustment\">xkb_key_repeat_rate</property><property name=\"digit"
  "s\">0</property><property name=\"value_pos\">right</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">3</property></packing></chi"
  "ld></object></child></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">1</property></packing></child></object></child></object></child><ch"
  "ild type=\"label\"><object class=\"GtkLabel\" id=\"label5\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">Typing Settings</pro"
  "perty><attributes><attribute name=\"weight\" value=\"bold\"/></attribut"
  "es></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkFrame\" i"
  "d=\"frame3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label_xalign\">0</property"
  "><property name=\"shadow_type\">none</property><child><object class=\"G"
  "tkAlignment\" id=\"alignment3\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"left_p"
  "adding\">12</property><child><object class=\"GtkVBox\" id=\"vbox4\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"border_width\">6</property><property name"
  "=\"spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"n"
  "et_cursor_blink_check\"><property name=\"label\" translatable=\"yes\">S"
  "how _blinking</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"tooltip_text\" translatable=\"yes\">Specify whet"
  "her or not the text cursor blinks</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkAlignment\" id=\"net_cursor_bl"
  "ink_box\"><property name=\"visible\">True</property><property name=\"se"
  "nsitive\">False</property><property name=\"can_focus\">False</property>"
  "<property name=\"left_padding\">18</property><child><object class=\"Gtk"
  "VBox\" id=\"vbox7\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label13\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"xalign\">0</property><property name=\"label\" translatab"
  "le=\"yes\">Blink _delay:</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"mnemonic_widget\">net_cursor_blink_time_sc"
  "ale</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkHScale\" id=\"n"
  "et_cursor_blink_time_scale\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"tooltip_te"
  "xt\" translatable=\"yes\">The delay, in milliseconds, between successiv"
  "e blinks of the cursor</property><property name=\"update_policy\">delay"
  "ed</property><property name=\"adjustment\">net_cursor_blink_time</prope"
  "rty><property name=\"digits\">0</property><property name=\"value_pos\">"
  "right</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child></object></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "</child></object></child><child type=\"label\"><object class=\"GtkLabel"
  "\" id=\"label6\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">Cursor</property><attributes><attribute name=\"weight\" value=\""
  "bold\"/></attributes></object></child></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">2</property></packing></child><child><object clas"
  "s=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"spacing\">1"
  "2</property><child><object class=\"GtkLabel\" id=\"label12\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"label\" translatable=\"yes\">_Test area:</proper"
  "ty><property name=\"use_underline\">True</property><property name=\"mne"
  "monic_widget\">entry1</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkEntry\" id=\"entry1\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"invisible_char\""
  ">\342\200\242</property><property name=\"invisible_char_set\">True</pro"
  "perty><property name=\"primary_icon_activatable\">False</property><prop"
  "erty name=\"secondary_icon_activatable\">False</property><property name"
  "=\"primary_icon_sensitive\">True</property><property name=\"secondary_i"
  "con_sensitive\">True</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">3</property></packing></child></object></"
  "child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">Beha_vior</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"tab_fill\">False</property></packing></child><child>"
  "<object class=\"GtkVBox\" id=\"vbox5\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">12</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label14\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"xalign\">0</property><property name=\"label\" translatable=\"yes"
  "\">Define shortcuts for la_unching applications:</property><property na"
  "me=\"use_underline\">True</property><property name=\"mnemonic_widget\">"
  "kbd_shortcuts_view</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkS"
  "crolledWindow\" id=\"scrolledwindow2\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "hscrollbar_policy\">automatic</property><property name=\"vscrollbar_pol"
  "icy\">automatic</property><property name=\"shadow_type\">etched-in</pro"
  "perty><child><object class=\"GtkTreeView\" id=\"kbd_shortcuts_view\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"search_column\">0</property></object></ch"
  "ild></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child><child><object class=\"GtkAlignment\" id=\"alignment8"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"yalign\">0</property><property name"
  "=\"xscale\">0</property><property name=\"yscale\">0</property><child><o"
  "bject class=\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"s"
  "pacing\">12</property><child><object class=\"GtkButton\" id=\"add_short"
  "cut_button\"><property name=\"label\">gtk-add</property><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">True</property><property name=\"use_stock\">True<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkButton\" id=\"edit_"
  "shortcut_button\"><property name=\"label\">gtk-edit</property><property"
  " name=\"use_action_appearance\">False</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">True</property><property name=\"use_stock\""
  ">True</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkButton\" id=\"d"
  "elete_shortcut_button\"><property name=\"label\">gtk-remove</property><"
  "property name=\"use_action_appearance\">False</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">True</property><property name=\"use"
  "_stock\">True</property></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">2</property></packing></child><child><object class=\"GtkButto"
  "n\" id=\"reset_shortcuts_button\"><property name=\"label\" translatable"
  "=\"yes\">Reset to _Defaults</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">True</property><property name=\"image\">image1</property><property "
  "name=\"use_underline\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"padding\">15</property><property name=\"position\">3</prop"
  "erty></packing></child></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">2</property></packing></child></object><packi"
  "ng><property name=\"position\">1</property></packing></child><child typ"
  "e=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">A_pplication Shortcuts</prope"
  "rty><property name=\"use_underline\">True</property></object><packing><"
  "property name=\"position\">1</property><property name=\"tab_fill\">Fals"
  "e</property></packing></child><child><object class=\"GtkVBox\" id=\"xkb"
  "_tab_layout_vbox\"><property name=\"can_focus\">False</property><proper"
  "ty name=\"border_width\">12</property><property name=\"spacing\">6</pro"
  "perty><child><object class=\"GtkCheckButton\" id=\"xkb_use_system_defau"
  "lt_checkbutton\"><property name=\"label\" translatable=\"yes\">_Use sys"
  "tem defaults</property><property name=\"use_action_appearance\">False</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">False</prop"
  "erty><property name=\"tooltip_text\" translatable=\"yes\">Specifies whe"
  "ther the keyboard layout is controlled with this settings dialog, or by"
  " the X server</property><property name=\"use_underline\">True</property"
  "><property name=\"active\">True</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkFrame\" i"
  "d=\"xkb_model_frame\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label_xalign\">0"
  "</property><property name=\"shadow_type\">none</property><child><object"
  " class=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><property name=\"left_padding\">12</prop"
  "erty><child><object class=\"GtkComboBox\" id=\"xkb_model_combo\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property></object></child></object></child><child type=\"label\"><obje"
  "ct class=\"GtkLabel\" id=\"label11\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">_Keyboard model</property><property name=\""
  "use_underline\">True</property><attributes><attribute name=\"weight\" v"
  "alue=\"bold\"/></attributes></object></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child><child><obj"
  "ect class=\"GtkHBox\" id=\"hbox4\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"spa"
  "cing\">6</property><property name=\"homogeneous\">True</property><child"
  "><object class=\"GtkFrame\" id=\"xkb_grpkey_frame\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment6\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkComboBox\""
  " id=\"xkb_grpkey_combo\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property></object></child></object></ch"
  "ild><child type=\"label\"><object class=\"GtkLabel\" id=\"label1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">Change la_you"
  "t option</property><property name=\"use_underline\">True</property><att"
  "ributes><attribute name=\"weight\" value=\"bold\"/></attributes></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkFrame\" id=\"xkb_com"
  "posekey_frame\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label_xalign\">0</prop"
  "erty><property name=\"shadow_type\">none</property><child><object class"
  "=\"GtkAlignment\" id=\"alignment7\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"bo"
  "rder_width\">6</property><property name=\"left_padding\">12</property><"
  "child><object class=\"GtkComboBox\" id=\"xkb_composekey_combo\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label15\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">Co_mpose key</property><property name=\"use_"
  "underline\">True</property><attributes><attribute name=\"weight\" value"
  "=\"bold\"/></attributes></object></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">2</property></packing></child>"
  "<child><object class=\"GtkFrame\" id=\"xkb_layout_frame\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label_xalign\">0</property><property name=\"shadow_"
  "type\">none</property><child><object class=\"GtkAlignment\" id=\"alignm"
  "ent4\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"border_width\">6</property><pro"
  "perty name=\"left_padding\">12</property><child><object class=\"GtkVBox"
  "\" id=\"vbox8\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"spacing\">6</property>"
  "<child><object class=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkScrolledWindow\""
  " id=\"scrolledwindow1\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"hscrollbar_poli"
  "cy\">automatic</property><property name=\"vscrollbar_policy\">automatic"
  "</property><property name=\"shadow_type\">etched-in</property><child><o"
  "bject class=\"GtkTreeView\" id=\"xkb_layout_view\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"search_column\">0</property></object></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkVBox\" id=\"vbuttonbox1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"spacing\">6</property><child><object class=\"GtkButton\" "
  "id=\"xkb_layout_up_button\"><property name=\"use_action_appearance\">Fa"
  "lse</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">True</"
  "property><property name=\"tooltip_text\" translatable=\"yes\">Move curr"
  "ently selected item up by one row</property><child><object class=\"GtkI"
  "mage\" id=\"image4\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"stock\">gtk-go-up"
  "</property></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkB"
  "utton\" id=\"xkb_layout_down_button\"><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">True</property><property name=\"tooltip_text\" translatable=\"yes\""
  ">Move currently selected item down by one row</property><child><object "
  "class=\"GtkImage\" id=\"image3\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"stock"
  "\">gtk-go-down</property></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">1</property></packing></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkHButtonBox\" id=\"hbuttonbox"
  "2\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"spacing\">12</property><property n"
  "ame=\"layout_style\">start</property><child><object class=\"GtkButton\""
  " id=\"xkb_layout_add_button\"><property name=\"label\">gtk-add</propert"
  "y><property name=\"use_action_appearance\">False</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">True</property><property name=\""
  "use_stock\">True</property></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">False</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkBu"
  "tton\" id=\"xkb_layout_edit_button\"><property name=\"label\">gtk-edit<"
  "/property><property name=\"use_action_appearance\">False</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">True</property><property"
  " name=\"use_stock\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">1</property></packing></child><child><object class"
  "=\"GtkButton\" id=\"xkb_layout_delete_button\"><property name=\"label\""
  ">gtk-delete</property><property name=\"use_action_appearance\">False</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">True</proper"
  "ty><property name=\"use_stock\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">2</property></packing></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object></child></object></child><child type=\"label\"><object "
  "class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">Key_board layout</property><property name=\"use"
  "_underline\">True</property><attributes><attribute name=\"weight\" valu"
  "e=\"bold\"/></attributes></object></child></object><packing><property n"
  "ame=\"expand\">True</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">3</property></packing></child></object><packi"
  "ng><property name=\"position\">2</property></packing></child><child typ"
  "e=\"tab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">_Layout</property><property n"
  "ame=\"use_underline\">True</property></object><packing><property name=\""
  "position\">2</property><property name=\"tab_fill\">False</property></pa"
  "cking></child></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">1<"
  "/property></packing></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object></child><action-widge"
  "ts><action-widget response=\"-11\">button1</action-widget><action-widge"
  "t response=\"0\">button2</action-widget></action-widgets></object><obje"
  "ct class=\"GtkAdjustment\" id=\"net_cursor_blink_time\"><property name="
  "\"lower\">100</property><property name=\"upper\">2000</property><proper"
  "ty name=\"value\">1000</property><property name=\"step_increment\">1</p"
  "roperty><property name=\"page_increment\">10</property></object><object"
  " class=\"GtkAdjustment\" id=\"xkb_key_repeat_delay\"><property name=\"l"
  "ower\">10</property><property name=\"upper\">1000</property><property n"
  "ame=\"value\">500</property><property name=\"step_increment\">1</proper"
  "ty><property name=\"page_increment\">10</property></object><object clas"
  "s=\"GtkAdjustment\" id=\"xkb_key_repeat_rate\"><property name=\"lower\""
  ">1</property><property name=\"upper\">250</property><property name=\"va"
  "lue\">20</property><property name=\"step_increment\">1</property><prope"
  "rty name=\"page_increment\">10</property></object><object class=\"GtkSi"
  "zeGroup\" id=\"sizegroup1\"/></interface>"
};

static const unsigned keyboard_dialog_ui_length = 33626u;

