/* automatically generated from appearance-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (appearance_dialog_ui)
#endif
#ifdef __GNUC__
static const char appearance_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char appearance_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"XfceTitledDialog\" id=\"dialog\""
  "><property name=\"can_focus\">False</property><property name=\"title\" "
  "translatable=\"yes\">Appearance</property><property name=\"window_posit"
  "ion\">center-on-parent</property><property name=\"icon_name\">preferenc"
  "es-desktop-theme</property><property name=\"type_hint\">dialog</propert"
  "y><property name=\"subtitle\" translatable=\"yes\">Customize the look o"
  "f your desktop</property><child internal-child=\"vbox\"><object class=\""
  "GtkVBox\" id=\"dialog-vbox1\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"spacing\""
  ">2</property><child internal-child=\"action_area\"><object class=\"GtkH"
  "ButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "layout_style\">end</property><child><object class=\"GtkButton\" id=\"bu"
  "tton1\"><property name=\"label\">gtk-close</property><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"use_stock\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkButton\" id=\"button2\""
  "><property name=\"label\">gtk-help</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">True</property><property name=\"use_stock\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property><pr"
  "operty name=\"secondary\">True</property></packing></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"pack_type\">end</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kNotebook\" id=\"plug-child\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"border_wi"
  "dth\">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrol"
  "ledwindow2\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"border_width\">12</property"
  "><property name=\"hscrollbar_policy\">automatic</property><property nam"
  "e=\"vscrollbar_policy\">automatic</property><property name=\"shadow_typ"
  "e\">etched-in</property><child><object class=\"GtkTreeView\" id=\"gtk_t"
  "heme_treeview\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"headers_visible\">False"
  "</property><property name=\"show_expanders\">False</property></object><"
  "/child></object></child><child type=\"tab\"><object class=\"GtkLabel\" "
  "id=\"label1\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">St_yle</property><property name=\"use_underline\">True</property><"
  "/object><packing><property name=\"tab_fill\">False</property></packing>"
  "</child><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindow1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"border_width\">12</property><propert"
  "y name=\"hscrollbar_policy\">automatic</property><property name=\"vscro"
  "llbar_policy\">automatic</property><property name=\"shadow_type\">etche"
  "d-in</property><child><object class=\"GtkTreeView\" id=\"icon_theme_tre"
  "eview\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"headers_visible\">False</proper"
  "ty><property name=\"show_expanders\">False</property></object></child><"
  "/object><packing><property name=\"position\">1</property></packing></ch"
  "ild><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">_Icons</propert"
  "y><property name=\"use_underline\">True</property></object><packing><pr"
  "operty name=\"position\">1</property><property name=\"tab_fill\">False<"
  "/property></packing></child><child><object class=\"GtkVBox\" id=\"vbox3"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"border_width\">12</property><proper"
  "ty name=\"spacing\">12</property><child><object class=\"GtkFrame\" id=\""
  "frame3\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label_xalign\">0</property><p"
  "roperty name=\"shadow_type\">none</property><child><object class=\"GtkA"
  "lignment\" id=\"alignment3\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"border_wi"
  "dth\">6</property><property name=\"bottom_padding\">6</property><proper"
  "ty name=\"left_padding\">12</property><child><object class=\"GtkFontBut"
  "ton\" id=\"gtk_fontname_button\"><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">T"
  "rue</property><property name=\"tooltip_text\" translatable=\"yes\">This"
  " font will be used as the default font used when drawing user interface"
  " text</property><property name=\"title\" translatable=\"yes\">Select a "
  "default font</property></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label7\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label\" translatable=\"yes\">Default Fon_t</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"mnemonic_widg"
  "et\">gtk_fontname_button</property><attributes><attribute name=\"weight"
  "\" value=\"bold\"/></attributes></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkFrame\" id=\"frame4\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label_xalign\">0</property><property name=\"shadow_type\">none</prop"
  "erty><child><object class=\"GtkAlignment\" id=\"alignment4\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"bottom_padding\">6</property><property name=\"le"
  "ft_padding\">12</property><child><object class=\"GtkTable\" id=\"table1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"border_width\">6</property><propert"
  "y name=\"n_rows\">3</property><property name=\"n_columns\">2</property>"
  "<property name=\"column_spacing\">12</property><property name=\"row_spa"
  "cing\">6</property><child><object class=\"GtkComboBox\" id=\"xft_hintin"
  "g_style_combo_box\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"tooltip_text\" tra"
  "nslatable=\"yes\">Many fonts contain information that provides extra hi"
  "nts as to how best draw the font; pick whichever looks best according t"
  "o personal preference</property><property name=\"model\">liststore1</pr"
  "operty><child><object class=\"GtkCellRendererText\" id=\"cellrendererte"
  "xt1\"/><attributes><attribute name=\"text\">0</attribute></attributes><"
  "/child></object><packing><property name=\"left_attach\">1</property><pr"
  "operty name=\"right_attach\">2</property><property name=\"top_attach\">"
  "1</property><property name=\"bottom_attach\">2</property></packing></ch"
  "ild><child><object class=\"GtkComboBox\" id=\"xft_rgba_combo_box\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"tooltip_text\" translatable=\"yes\">Font q"
  "uality on a TFT or LCD screen can be greatly improved by choosing the c"
  "orrect sub-pixel order of the screen</property><property name=\"model\""
  ">xft_rgba_store</property><child><object class=\"GtkCellRendererText\" "
  "id=\"cellrenderertext3\"/><attributes><attribute name=\"text\">1</attri"
  "bute></attributes></child><child><object class=\"GtkCellRendererPixbuf\""
  " id=\"cellrendererpixbuf1\"/><attributes><attribute name=\"pixbuf\">0</"
  "attribute></attributes></child></object><packing><property name=\"left_"
  "attach\">1</property><property name=\"right_attach\">2</property><prope"
  "rty name=\"top_attach\">2</property><property name=\"bottom_attach\">3<"
  "/property></packing></child><child><object class=\"GtkLabel\" id=\"labe"
  "l11\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"xalign\">1</property><property n"
  "ame=\"label\" translatable=\"yes\">Sub-_pixel order:</property><propert"
  "y name=\"use_underline\">True</property><property name=\"mnemonic_widge"
  "t\">xft_rgba_combo_box</property></object><packing><property name=\"top"
  "_attach\">2</property><property name=\"bottom_attach\">3</property><pro"
  "perty name=\"x_options\">GTK_FILL</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"label10\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"xalign\">0</property><property name=\"label\" translatable=\"yes\">Hi"
  "ntin_g:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">xft_hinting_style_combo_box</property></o"
  "bject><packing><property name=\"top_attach\">1</property><property name"
  "=\"bottom_attach\">2</property><property name=\"x_options\">GTK_FILL</p"
  "roperty></packing></child><child><object class=\"GtkCheckButton\" id=\""
  "xft_antialias_check_button\"><property name=\"label\" translatable=\"ye"
  "s\">_Enable anti-aliasing</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"tooltip_text\" translatable=\"yes\">A"
  "nti-aliasing, or font smoothing, can improve the look of text on the sc"
  "reen</property><property name=\"use_underline\">True</property><propert"
  "y name=\"active\">True</property><property name=\"draw_indicator\">True"
  "</property></object><packing><property name=\"right_attach\">2</propert"
  "y></packing></child></object></child></object></child><child type=\"lab"
  "el\"><object class=\"GtkLabel\" id=\"label8\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Rendering</property><attributes><at"
  "tribute name=\"weight\" value=\"bold\"/></attributes></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child><child><object class=\"GtkFrame\" id=\"frame5\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label_xalign\">0</property><property name=\"sha"
  "dow_type\">none</property><child><object class=\"GtkAlignment\" id=\"al"
  "ignment5\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"bottom_padding\">6</propert"
  "y><property name=\"left_padding\">12</property><child><object class=\"G"
  "tkHBox\" id=\"hbox1\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"border_width\">6"
  "</property><property name=\"spacing\">12</property><child><object class"
  "=\"GtkCheckButton\" id=\"xft_custom_dpi_check_button\"><property name=\""
  "label\" translatable=\"yes\">Custom _DPI setting:</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"tooltip_text\""
  " translatable=\"yes\">Override the detected monitor resolution if fonts"
  " look too large or too small</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkSpinButton\" id=\"xft_custom_dpi_spi"
  "n_button\"><property name=\"visible\">True</property><property name=\"s"
  "ensitive\">False</property><property name=\"can_focus\">True</property>"
  "<property name=\"primary_icon_activatable\">False</property><property n"
  "ame=\"secondary_icon_activatable\">False</property><property name=\"pri"
  "mary_icon_sensitive\">True</property><property name=\"secondary_icon_se"
  "nsitive\">True</property><property name=\"adjustment\">xft_custom_dpi</"
  "property><property name=\"snap_to_ticks\">True</property><property name"
  "=\"numeric\">True</property><property name=\"update_policy\">if-valid</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label9\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label\" translatable=\"yes\">DPI</property><attributes><attr"
  "ibute name=\"weight\" value=\"bold\"/></attributes></object></child></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"position\">2</property></pack"
  "ing></child></object><packing><property name=\"position\">2</property><"
  "/packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"la"
  "bel3\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">_F"
  "onts</property><property name=\"use_underline\">True</property></object"
  "><packing><property name=\"position\">2</property><property name=\"tab_"
  "fill\">False</property></packing></child><child><object class=\"GtkVBox"
  "\" id=\"vbox1\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"border_width\">12</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Frame\" id=\"frame2\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label_xalign\">0"
  "</property><property name=\"shadow_type\">none</property><child><object"
  " class=\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><property name=\"bottom_padding\">6</pro"
  "perty><property name=\"left_padding\">12</property><child><object class"
  "=\"GtkComboBox\" id=\"gtk_toolbar_style_combo_box\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"tooltip_text\" translatable=\"yes\">Specify what should b"
  "e displayed in toolbar items</property><property name=\"model\">liststo"
  "re2</property><child><object class=\"GtkCellRendererText\" id=\"cellren"
  "derertext2\"/><attributes><attribute name=\"text\">0</attribute></attri"
  "butes></child></object></child></object></child><child type=\"label\"><"
  "object class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">_Toolbar Style</property><property name="
  "\"use_underline\">True</property><property name=\"mnemonic_widget\">gtk"
  "_toolbar_style_combo_box</property><attributes><attribute name=\"weight"
  "\" value=\"bold\"/></attributes></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label_xalign\">0</property><property name=\"shadow_type\">none</prop"
  "erty><child><object class=\"GtkAlignment\" id=\"alignment1\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"bottom_padding\">6</property><property name=\"le"
  "ft_padding\">12</property><child><object class=\"GtkVBox\" id=\"vbox2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkCheckButton\" id"
  "=\"gtk_button_images_check_button\"><property name=\"label\" translatab"
  "le=\"yes\">Show images on _buttons</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Specify whether icons should be displayed next to text in butt"
  "ons</property><property name=\"use_underline\">True</property><property"
  " name=\"draw_indicator\">True</property></object><packing><property nam"
  "e=\"expand\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkCheckButton\" id=\"gtk_menu_images_check_button\"><property na"
  "me=\"label\" translatable=\"yes\">Show images in _menus</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"toolti"
  "p_text\" translatable=\"yes\">Specify whether icons should be displayed"
  " next to items in menus</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"gtk_caneditaccels_check"
  "_button\"><property name=\"label\" translatable=\"yes\">Enable e_ditabl"
  "e accelerators</property><property name=\"use_action_appearance\">False"
  "</property><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"receives_default\">False</pr"
  "operty><property name=\"tooltip_text\" translatable=\"yes\">If selected"
  ", keyboard shortcuts for menu items can be changed by hovering the mous"
  "e over the menu item and pressing the new key combination for the short"
  "cut</property><property name=\"use_underline\">True</property><property"
  " name=\"draw_indicator\">True</property></object><packing><property nam"
  "e=\"expand\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">2</property></packing></child></object></child>"
  "</object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label5\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "Menus and Buttons</property><attributes><attribute name=\"weight\" valu"
  "e=\"bold\"/></attributes></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child><child><object"
  " class=\"GtkFrame\" id=\"event_sounds_frame\"><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment6\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"bottom_padding"
  "\">6</property><property name=\"left_padding\">12</property><child><obj"
  "ect class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"bor"
  "der_width\">6</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkCheckButton\" id=\"enable_event_sounds_check_button\""
  "><property name=\"label\" translatable=\"yes\">Enable _event sounds</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"tooltip_text\" translatable=\"yes\">Enable or disable event sound"
  "s globally (requires \"Canberra\" support)</property><property name=\"u"
  "se_underline\">True</property><property name=\"draw_indicator\">True</p"
  "roperty></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkCheckButton\" id=\"ena"
  "ble_input_feedback_sounds_button\"><property name=\"label\" translatabl"
  "e=\"yes\">Enable input feedbac_k sounds</property><property name=\"use_"
  "action_appearance\">False</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">Specify whether mouse clicks and other user input will ca"
  "use event sounds to play</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">3</property></packing></c"
  "hild></object></child></object></child><child type=\"label\"><object cl"
  "ass=\"GtkLabel\" id=\"label4\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">Event sounds</property><attributes><attribute nam"
  "e=\"weight\" value=\"bold\"/></attributes></object></child></object><pa"
  "cking><property name=\"expand\">True</property><property name=\"fill\">"
  "True</property><property name=\"position\">2</property></packing></chil"
  "d></object><packing><property name=\"position\">3</property></packing><"
  "/child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label12\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"label\" translatable=\"yes\">Setti_ngs</"
  "property><property name=\"use_underline\">True</property></object><pack"
  "ing><property name=\"position\">3</property><property name=\"tab_fill\""
  ">False</property></packing></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">1</property></packing></child></object></child><acti"
  "on-widgets><action-widget response=\"0\">button1</action-widget><action"
  "-widget response=\"-11\">button2</action-widget></action-widgets></obje"
  "ct><object class=\"GtkListStore\" id=\"liststore1\"><columns><column ty"
  "pe=\"gchararray\"/></columns><data><row><col id=\"0\" translatable=\"ye"
  "s\">None</col></row><row><col id=\"0\" translatable=\"yes\">Slight</col"
  "></row><row><col id=\"0\" translatable=\"yes\">Medium</col></row><row><"
  "col id=\"0\" translatable=\"yes\">Full</col></row></data></object><obje"
  "ct class=\"GtkListStore\" id=\"liststore2\"><columns><column type=\"gch"
  "ararray\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Icon"
  "s</col></row><row><col id=\"0\" translatable=\"yes\">Text</col></row><r"
  "ow><col id=\"0\" translatable=\"yes\">Text under icons</col></row><row>"
  "<col id=\"0\" translatable=\"yes\">Text next to icons</col></row></data"
  "></object><object class=\"GtkAdjustment\" id=\"xft_custom_dpi\"><proper"
  "ty name=\"lower\">48</property><property name=\"upper\">1000</property>"
  "<property name=\"value\">96</property><property name=\"step_increment\""
  ">1</property><property name=\"page_increment\">10</property></object><o"
  "bject class=\"GtkListStore\" id=\"xft_rgba_store\"><columns><column typ"
  "e=\"GdkPixbuf\"/><column type=\"gchararray\"/></columns></object></inte"
  "rface>"
};

static const unsigned appearance_dialog_ui_length = 22846u;

