/* automatically generated from appearance-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (appearance_dialog_ui)
#endif
#ifdef __GNUC__
static const char appearance_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char appearance_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"XfceTitledDialog\" id=\"dialog\""
  "><property name=\"can_focus\">False</property><property name=\"title\" "
  "translatable=\"yes\">Appearance</property><property name=\"window_posit"
  "ion\">center-on-parent</property><property name=\"icon_name\">preferenc"
  "es-desktop-theme</property><property name=\"type_hint\">dialog</propert"
  "y><property name=\"subtitle\" translatable=\"yes\">Customize the look o"
  "f your desktop</property><child internal-child=\"vbox\"><object class=\""
  "GtkVBox\" id=\"dialog-vbox1\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"spacing\""
  ">2</property><child internal-child=\"action_area\"><object class=\"GtkH"
  "ButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "layout_style\">end</property><child><object class=\"GtkButton\" id=\"bu"
  "tton2\"><property name=\"label\">gtk-help</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"use_act"
  "ion_appearance\">False</property><property name=\"use_stock\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty><property name=\"secondary\">True</property></packing></child><chil"
  "d><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">g"
  "tk-close</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">T"
  "rue</property><property name=\"use_action_appearance\">False</property>"
  "<property name=\"use_stock\">True</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">0</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"pack_type\">end</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kNotebook\" id=\"plug-child\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"border_wi"
  "dth\">6</property><child><object class=\"GtkScrolledWindow\" id=\"scrol"
  "ledwindow2\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"border_width\">12</property"
  "><property name=\"hscrollbar_policy\">automatic</property><property nam"
  "e=\"vscrollbar_policy\">automatic</property><property name=\"shadow_typ"
  "e\">etched-in</property><child><object class=\"GtkTreeView\" id=\"gtk_t"
  "heme_treeview\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"headers_visible\">False"
  "</property><property name=\"show_expanders\">False</property></object><"
  "/child></object></child><child type=\"tab\"><object class=\"GtkLabel\" "
  "id=\"label1\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">St_yle</property><property name=\"use_underline\">True</property><"
  "/object><packing><property name=\"tab_fill\">False</property></packing>"
  "</child><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindow1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"border_width\">12</property><propert"
  "y name=\"hscrollbar_policy\">automatic</property><property name=\"vscro"
  "llbar_policy\">automatic</property><property name=\"shadow_type\">etche"
  "d-in</property><child><object class=\"GtkTreeView\" id=\"icon_theme_tre"
  "eview\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"headers_visible\">False</proper"
  "ty><property name=\"show_expanders\">False</property></object></child><"
  "/object><packing><property name=\"position\">1</property></packing></ch"
  "ild><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">_Icons</propert"
  "y><property name=\"use_underline\">True</property></object><packing><pr"
  "operty name=\"position\">1</property><property name=\"tab_fill\">False<"
  "/property></packing></child><child><object class=\"GtkVBox\" id=\"vbox3"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"border_width\">12</property><proper"
  "ty name=\"spacing\">12</property><child><object class=\"GtkFrame\" id=\""
  "frame3\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label_xalign\">0</property><p"
  "roperty name=\"shadow_type\">none</property><child><object class=\"GtkA"
  "lignment\" id=\"alignment3\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"border_wi"
  "dth\">6</property><property name=\"bottom_padding\">6</property><proper"
  "ty name=\"left_padding\">12</property><child><object class=\"GtkFontBut"
  "ton\" id=\"gtk_fontname_button\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">True</property><property name=\"tooltip_text\" translatabl"
  "e=\"yes\">This font will be used as the default font used when drawing "
  "user interface text</property><property name=\"use_action_appearance\">"
  "False</property><property name=\"title\" translatable=\"yes\">Select a "
  "default font</property></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label7\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label\" translatable=\"yes\">Default Fon_t</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"mnemonic_widg"
  "et\">gtk_fontname_button</property><attributes><attribute name=\"weight"
  "\" value=\"bold\"/></attributes></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">0</property></packing></child><child>"
  "<object class=\"GtkFrame\" id=\"frame7\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label_xalign\">0</property><property name=\"shadow_type\">none</prop"
  "erty><child><object class=\"GtkAlignment\" id=\"alignment7\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"border_width\">6</property><property name=\"bott"
  "om_padding\">6</property><property name=\"left_padding\">12</property><"
  "child><object class=\"GtkFontButton\" id=\"gtk_monospace_fontname_butto"
  "n\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">True</property><"
  "property name=\"tooltip_text\" translatable=\"yes\">This font will be u"
  "sed as the default monospace font, for example by terminal emulators.</"
  "property><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"title\" translatable=\"yes\">Select a default monospace fon"
  "t</property><property name=\"font_name\">Monospace 12</property></objec"
  "t></child></object></child><child type=\"label\"><object class=\"GtkLab"
  "el\" id=\"label14\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label\" translatab"
  "le=\"yes\">Default _Monospace Font</property><property name=\"use_under"
  "line\">True</property><property name=\"mnemonic_widget\">gtk_monospace_"
  "fontname_button</property><attributes><attribute name=\"weight\" value="
  "\"bold\"/></attributes></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">1</property></packing></child><child><object c"
  "lass=\"GtkFrame\" id=\"frame4\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label_"
  "xalign\">0</property><property name=\"shadow_type\">none</property><chi"
  "ld><object class=\"GtkAlignment\" id=\"alignment4\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"bottom_padding\">6</property><property name=\"left_paddin"
  "g\">12</property><child><object class=\"GtkTable\" id=\"table1\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"border_width\">6</property><property name=\""
  "n_rows\">3</property><property name=\"n_columns\">2</property><property"
  " name=\"column_spacing\">12</property><property name=\"row_spacing\">6<"
  "/property><child><object class=\"GtkComboBox\" id=\"xft_hinting_style_c"
  "ombo_box\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Many fonts contain information that provides extra hints as to"
  " how best draw the font; pick whichever looks best according to persona"
  "l preference</property><property name=\"model\">liststore1</property><c"
  "hild><object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><a"
  "ttributes><attribute name=\"text\">0</attribute></attributes></child></"
  "object><packing><property name=\"left_attach\">1</property><property na"
  "me=\"right_attach\">2</property><property name=\"top_attach\">1</proper"
  "ty><property name=\"bottom_attach\">2</property></packing></child><chil"
  "d><object class=\"GtkComboBox\" id=\"xft_rgba_combo_box\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"tooltip_text\" translatable=\"yes\">Font quality on"
  " a TFT or LCD screen can be greatly improved by choosing the correct su"
  "b-pixel order of the screen</property><property name=\"model\">xft_rgba"
  "_store</property><child><object class=\"GtkCellRendererText\" id=\"cell"
  "renderertext3\"/><attributes><attribute name=\"text\">1</attribute></at"
  "tributes></child><child><object class=\"GtkCellRendererPixbuf\" id=\"ce"
  "llrendererpixbuf1\"/><attributes><attribute name=\"pixbuf\">0</attribut"
  "e></attributes></child></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"right_attach\">2</property><property name"
  "=\"top_attach\">2</property><property name=\"bottom_attach\">3</propert"
  "y></packing></child><child><object class=\"GtkLabel\" id=\"label11\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"xalign\">1</property><property name=\"la"
  "bel\" translatable=\"yes\">Sub-_pixel order:</property><property name=\""
  "use_underline\">True</property><property name=\"mnemonic_widget\">xft_r"
  "gba_combo_box</property></object><packing><property name=\"top_attach\""
  ">2</property><property name=\"bottom_attach\">3</property><property nam"
  "e=\"x_options\">GTK_FILL</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label10\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">Hintin_g:</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"mnemonic_widget\">xft_hinting_style_combo_box</property></object><pac"
  "king><property name=\"top_attach\">1</property><property name=\"bottom_"
  "attach\">2</property><property name=\"x_options\">GTK_FILL</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"xft_antial"
  "ias_check_button\"><property name=\"label\" translatable=\"yes\">_Enabl"
  "e anti-aliasing</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">False</property><property name=\"tooltip_text\" translatable=\"ye"
  "s\">Anti-aliasing, or font smoothing, can improve the look of text on t"
  "he screen</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "active\">True</property><property name=\"draw_indicator\">True</propert"
  "y></object><packing><property name=\"right_attach\">2</property></packi"
  "ng></child></object></child></object></child><child type=\"label\"><obj"
  "ect class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">Rendering</property><attributes><attribute "
  "name=\"weight\" value=\"bold\"/></attributes></object></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">2</property></packing></"
  "child><child><object class=\"GtkFrame\" id=\"frame5\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment5"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"bottom_padding\">6</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"GtkHBox\""
  " id=\"hbox1\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"border_width\">6</proper"
  "ty><property name=\"spacing\">12</property><child><object class=\"GtkCh"
  "eckButton\" id=\"xft_custom_dpi_check_button\"><property name=\"label\""
  " translatable=\"yes\">Custom _DPI setting:</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"toolt"
  "ip_text\" translatable=\"yes\">Override the detected monitor resolution"
  " if fonts look too large or too small</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkSpinButton\" id=\"xft_custom_dpi_spin_butt"
  "on\"><property name=\"visible\">True</property><property name=\"sensiti"
  "ve\">False</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"primary_icon_activatable\">False</property><property name=\""
  "secondary_icon_activatable\">False</property><property name=\"primary_i"
  "con_sensitive\">True</property><property name=\"secondary_icon_sensitiv"
  "e\">True</property><property name=\"adjustment\">xft_custom_dpi</proper"
  "ty><property name=\"snap_to_ticks\">True</property><property name=\"num"
  "eric\">True</property><property name=\"update_policy\">if-valid</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">1</property>"
  "</packing></child></object></child></object></child><child type=\"label"
  "\"><object class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label\" translatable=\"yes\">DPI</property><attributes><attribute"
  " name=\"weight\" value=\"bold\"/></attributes></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">3</property></packing><"
  "/child></object><packing><property name=\"position\">2</property></pack"
  "ing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label3\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">_Fonts</"
  "property><property name=\"use_underline\">True</property></object><pack"
  "ing><property name=\"position\">2</property><property name=\"tab_fill\""
  ">False</property></packing></child><child><object class=\"GtkVBox\" id="
  "\"vbox1\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"border_width\">12</property>"
  "<property name=\"spacing\">6</property><child><object class=\"GtkFrame\""
  " id=\"frame2\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label_xalign\">0</prope"
  "rty><property name=\"shadow_type\">none</property><child><object class="
  "\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"bor"
  "der_width\">6</property><property name=\"bottom_padding\">6</property><"
  "property name=\"left_padding\">12</property><child><object class=\"GtkC"
  "omboBox\" id=\"gtk_toolbar_style_combo_box\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">Specify what should be displ"
  "ayed in toolbar items</property><property name=\"model\">liststore2</pr"
  "operty><child><object class=\"GtkCellRendererText\" id=\"cellrendererte"
  "xt2\"/><attributes><attribute name=\"text\">0</attribute></attributes><"
  "/child></object></child></object></child><child type=\"label\"><object "
  "class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">_Toolbar Style</property><property name=\"use_u"
  "nderline\">True</property><property name=\"mnemonic_widget\">gtk_toolba"
  "r_style_combo_box</property><attributes><attribute name=\"weight\" valu"
  "e=\"bold\"/></attributes></object></child></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l_xalign\">0</property><property name=\"shadow_type\">none</property><c"
  "hild><object class=\"GtkAlignment\" id=\"alignment1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"bottom_padding\">6</property><property name=\"left_padd"
  "ing\">12</property><child><object class=\"GtkVBox\" id=\"vbox2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"border_width\">6</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"gtk_"
  "button_images_check_button\"><property name=\"label\" translatable=\"ye"
  "s\">Show images on _buttons</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">Specify whether icons should be displayed next to text "
  "in buttons</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kCheckButton\" id=\"gtk_menu_images_check_button\"><property name=\"lab"
  "el\" translatable=\"yes\">Show images in _menus</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property name=\""
  "tooltip_text\" translatable=\"yes\">Specify whether icons should be dis"
  "played next to items in menus</property><property name=\"use_action_app"
  "earance\">False</property><property name=\"use_underline\">True</proper"
  "ty><property name=\"draw_indicator\">True</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child><chil"
  "d><object class=\"GtkCheckButton\" id=\"gtk_caneditaccels_check_button\""
  "><property name=\"label\" translatable=\"yes\">Enable e_ditable acceler"
  "ators</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"receives_default\">Fals"
  "e</property><property name=\"tooltip_text\" translatable=\"yes\">If sel"
  "ected, keyboard shortcuts for menu items can be changed by hovering the"
  " mouse over the menu item and pressing the new key combination for the "
  "shortcut</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"d"
  "raw_indicator\">True</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">2</property></packing></child></object></child></object>"
  "</child><child type=\"label\"><object class=\"GtkLabel\" id=\"label5\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">Menus and"
  " Buttons</property><attributes><attribute name=\"weight\" value=\"bold\""
  "/></attributes></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child><child><object class=\"G"
  "tkFrame\" id=\"event_sounds_frame\"><property name=\"can_focus\">False<"
  "/property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment6\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"bottom_padding\">6</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"border_width\">"
  "6</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkCheckButton\" id=\"enable_event_sounds_check_button\"><property n"
  "ame=\"label\" translatable=\"yes\">Enable _event sounds</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"tooltip_text\" translatable=\"yes\">Enable or disable event sou"
  "nds globally (requires \"Canberra\" support)</property><property name=\""
  "use_action_appearance\">False</property><property name=\"use_underline\""
  ">True</property><property name=\"draw_indicator\">True</property></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"enable_input_feed"
  "back_sounds_button\"><property name=\"label\" translatable=\"yes\">Enab"
  "le input feedbac_k sounds</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">Specify whether mouse clicks and other user input will ca"
  "use event sounds to play</property><property name=\"use_action_appearan"
  "ce\">False</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"draw_indicator\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">3</property></packing></child></object>"
  "</child></object></child><child type=\"label\"><object class=\"GtkLabel"
  "\" id=\"label4\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">Event sounds</property><attributes><attribute name=\"weight\" v"
  "alue=\"bold\"/></attributes></object></child></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">2</property></packing></child></object><pa"
  "cking><property name=\"position\">3</property></packing></child><child "
  "type=\"tab\"><object class=\"GtkLabel\" id=\"label12\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Setti_ngs</property><prope"
  "rty name=\"use_underline\">True</property></object><packing><property n"
  "ame=\"position\">3</property><property name=\"tab_fill\">False</propert"
  "y></packing></child></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">1</property></packing></child></object></child><action-widgets><act"
  "ion-widget response=\"-11\">button2</action-widget><action-widget respo"
  "nse=\"0\">button1</action-widget></action-widgets></object><object clas"
  "s=\"GtkListStore\" id=\"liststore1\"><columns><column type=\"gchararray"
  "\"/></columns><data><row><col id=\"0\" translatable=\"yes\">None</col><"
  "/row><row><col id=\"0\" translatable=\"yes\">Slight</col></row><row><co"
  "l id=\"0\" translatable=\"yes\">Medium</col></row><row><col id=\"0\" tr"
  "anslatable=\"yes\">Full</col></row></data></object><object class=\"GtkL"
  "istStore\" id=\"liststore2\"><columns><column type=\"gchararray\"/></co"
  "lumns><data><row><col id=\"0\" translatable=\"yes\">Icons</col></row><r"
  "ow><col id=\"0\" translatable=\"yes\">Text</col></row><row><col id=\"0\""
  " translatable=\"yes\">Text under icons</col></row><row><col id=\"0\" tr"
  "anslatable=\"yes\">Text next to icons</col></row></data></object><objec"
  "t class=\"GtkAdjustment\" id=\"xft_custom_dpi\"><property name=\"lower\""
  ">48</property><property name=\"upper\">1000</property><property name=\""
  "value\">96</property><property name=\"step_increment\">1</property><pro"
  "perty name=\"page_increment\">10</property></object><object class=\"Gtk"
  "ListStore\" id=\"xft_rgba_store\"><columns><column type=\"GdkPixbuf\"/>"
  "<column type=\"gchararray\"/></columns></object></interface>"
};

static const unsigned appearance_dialog_ui_length = 24465u;

