/* automatically generated from mouse-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (mouse_dialog_ui)
#endif
#ifdef __GNUC__
static const char mouse_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char mouse_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"GtkAdjustment\" id=\"dclick-dist"
  "ance\"><property name=\"upper\">20</property><property name=\"value\">4"
  "</property><property name=\"step_increment\">1</property><property name"
  "=\"page_increment\">5</property></object><object class=\"GtkAdjustment\""
  " id=\"dclick-time\"><property name=\"lower\">100</property><property na"
  "me=\"upper\">2000</property><property name=\"value\">250</property><pro"
  "perty name=\"step_increment\">1</property><property name=\"page_increme"
  "nt\">100</property></object><object class=\"GtkAdjustment\" id=\"device"
  "-acceleration\"><property name=\"lower\">0</property><property name=\"u"
  "pper\">10</property><property name=\"value\">2</property><property name"
  "=\"step_increment\">0.1</property><property name=\"page_increment\">1</"
  "property></object><object class=\"GtkAdjustment\" id=\"device-threshold"
  "\"><property name=\"lower\">1</property><property name=\"upper\">30</pr"
  "operty><property name=\"value\">4</property><property name=\"step_incre"
  "ment\">1</property><property name=\"page_increment\">5</property></obje"
  "ct><object class=\"GtkAdjustment\" id=\"dnd-threshold\"><property name="
  "\"lower\">1</property><property name=\"upper\">50</property><property n"
  "ame=\"value\">8</property><property name=\"step_increment\">1</property"
  "><property name=\"page_increment\">10</property></object><object class="
  "\"GtkImage\" id=\"image5\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"stock\">gtk"
  "-revert-to-saved</property></object><object class=\"GtkAdjustment\" id="
  "\"synaptics-disable-duration\"><property name=\"lower\">0.1</property><"
  "property name=\"upper\">4</property><property name=\"value\">2</propert"
  "y><property name=\"step_increment\">0.1</property><property name=\"page"
  "_increment\">1</property></object><object class=\"GtkListStore\" id=\"s"
  "ynaptics-scroll-store\"><columns><column type=\"gchararray\"/><column t"
  "ype=\"gboolean\"/></columns><data><row><col id=\"0\" translatable=\"yes"
  "\">Disabled</col><col id=\"1\">True</col></row><row><col id=\"0\" trans"
  "latable=\"yes\">Edge scrolling</col><col id=\"1\">True</col></row><row>"
  "<col id=\"0\" translatable=\"yes\">Two-finger scrolling</col><col id=\""
  "1\">True</col></row><row><col id=\"0\" translatable=\"yes\">Circular sc"
  "rolling</col><col id=\"1\">True</col></row></data></object><object clas"
  "s=\"GtkAdjustment\" id=\"theme-cursor-size\"><property name=\"lower\">1"
  "6</property><property name=\"upper\">48</property><property name=\"valu"
  "e\">24</property><property name=\"step_increment\">1</property><propert"
  "y name=\"page_increment\">11</property></object><object class=\"GtkList"
  "Store\" id=\"wacom-rotation-store\"><columns><column type=\"gint\"/><co"
  "lumn type=\"gchararray\"/></columns><data><row><col id=\"0\">0</col><co"
  "l id=\"1\" translatable=\"yes\">None (right-handed)</col></row><row><co"
  "l id=\"0\">3</col><col id=\"1\" translatable=\"yes\">Half (left-handed)"
  "</col></row><row><col id=\"0\">1</col><col id=\"1\" translatable=\"yes\""
  ">Clockwise</col></row><row><col id=\"0\">2</col><col id=\"1\" translata"
  "ble=\"yes\">Counterclockwise</col></row></data></object><object class=\""
  "XfceTitledDialog\" id=\"mouse-dialog\"><property name=\"can_focus\">Fal"
  "se</property><property name=\"title\" translatable=\"yes\">Mouse and To"
  "uchpad</property><property name=\"window_position\">center-on-parent</p"
  "roperty><property name=\"icon_name\">preferences-desktop-peripherals</p"
  "roperty><property name=\"type_hint\">dialog</property><property name=\""
  "subtitle\" translatable=\"yes\">Configure pointer device behavior and a"
  "ppearance</property><child internal-child=\"vbox\"><object class=\"GtkV"
  "Box\" id=\"dialog-vbox1\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"spacing\">2<"
  "/property><child internal-child=\"action_area\"><object class=\"GtkHBut"
  "tonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "yout_style\">end</property><child><object class=\"GtkButton\" id=\"butt"
  "on1\"><property name=\"label\">gtk-close</property><property name=\"use"
  "_action_appearance\">False</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"use_stock\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkButton\" id=\"button2\">"
  "<property name=\"label\">gtk-help</property><property name=\"use_action"
  "_appearance\">False</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">True</property><property name=\"use_stock\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">0</property><pro"
  "perty name=\"secondary\">True</property></packing></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"pack_type\">end</property><property nam"
  "e=\"position\">0</property></packing></child><child><object class=\"Gtk"
  "Notebook\" id=\"plug-child\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"border_wid"
  "th\">6</property><child><object class=\"GtkVBox\" id=\"vbox1\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"border_width\">12</property><property name=\"s"
  "pacing\">6</property><child><object class=\"GtkHBox\" id=\"hbox1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"spacing\">12</property><child><object clas"
  "s=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">De_vice:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">device-combobox</pro"
  "perty><property name=\"angle\">0.050000000000000003</property></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkComboBox\" id=\"device-combobox\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkCheck"
  "Button\" id=\"device-enabled\"><property name=\"label\" translatable=\""
  "yes\">_Enable this device</property><property name=\"use_action_appeara"
  "nce\">False</property><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkNotebook\" id=\"device-notebook\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><child><o"
  "bject class=\"GtkVBox\" id=\"device-box\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label_xalign\">0</property><property name=\"shadow_type\">none"
  "</property><child><object class=\"GtkAlignment\" id=\"alignment1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkVBox\" id=\"vbox12\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"borde"
  "r_width\">6</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkHBox\" id=\"hbox3\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"sp"
  "acing\">12</property><child><object class=\"GtkRadioButton\" id=\"devic"
  "e-right-handed\"><property name=\"label\" translatable=\"yes\">Ri_ght-h"
  "anded</property><property name=\"use_action_appearance\">False</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"active\">"
  "True</property><property name=\"draw_indicator\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkRadioButton\" id=\"device-left-handed"
  "\"><property name=\"label\" translatable=\"yes\">Le_ft-handed</property"
  "><property name=\"use_action_appearance\">False</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property><property name=\"group\">device-right-handed</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkCheckButton\" id=\"devi"
  "ce-reverse-scrolling\"><property name=\"label\" translatable=\"yes\">Re"
  "verse scroll d_irection</property><property name=\"use_action_appearanc"
  "e\">False</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "False</property><property name=\"tooltip_text\" translatable=\"yes\">Wh"
  "en selected, the scroll wheel will work in the opposite direction</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"d"
  "raw_indicator\">True</property></object><packing><property name=\"expan"
  "d\">True</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child></object></child></object>"
  "</child><child type=\"label\"><object class=\"GtkLabel\" id=\"label14\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Buttons<"
  "/property><attributes><attribute name=\"weight\" value=\"bold\"/></attr"
  "ibutes></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkFrame\""
  " id=\"frame2\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label_xalign\">0</prope"
  "rty><property name=\"shadow_type\">none</property><child><object class="
  "\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkTable\" id=\"table1\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"n_rows\">3</property><property name=\"n_columns\">2</property><p"
  "roperty name=\"column_spacing\">12</property><property name=\"row_spaci"
  "ng\">6</property><child><object class=\"GtkLabel\" id=\"device-accelera"
  "tion-label\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"xalign\">0</property><prop"
  "erty name=\"label\" translatable=\"yes\">Acceleratio_n:</property><prop"
  "erty name=\"use_underline\">True</property><property name=\"mnemonic_wi"
  "dget\">device-acceleration-scale</property></object><packing><property "
  "name=\"x_options\">GTK_FILL</property><property name=\"y_options\">GTK_"
  "FILL</property></packing></child><child><object class=\"GtkHScale\" id="
  "\"device-acceleration-scale\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"tooltip_t"
  "ext\" translatable=\"yes\">The factor at which the pointer\'s speed wil"
  "l increase as the mouse is moved</property><property name=\"update_poli"
  "cy\">delayed</property><property name=\"adjustment\">device-acceleratio"
  "n</property><property name=\"round_digits\">1</property><property name="
  "\"value_pos\">right</property></object><packing><property name=\"left_a"
  "ttach\">1</property><property name=\"right_attach\">2</property></packi"
  "ng></child><child><object class=\"GtkHScale\" id=\"device-threshold-sca"
  "le\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"tooltip_text\" translatable=\"yes\""
  ">The number of pixels the pointer must move in a short time before it s"
  "tarts accelerating</property><property name=\"update_policy\">delayed</"
  "property><property name=\"adjustment\">device-threshold</property><prop"
  "erty name=\"round_digits\">0</property><property name=\"digits\">0</pro"
  "perty><property name=\"value_pos\">right</property></object><packing><p"
  "roperty name=\"left_attach\">1</property><property name=\"right_attach\""
  ">2</property><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property></packing></child><child><object class=\"Gt"
  "kLabel\" id=\"device-threshold-label\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">Sens"
  "itivit_y:</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"mnemonic_widget\">device-threshold-scale</property></obje"
  "ct><packing><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property><property name=\"x_options\">GTK_FILL</prop"
  "erty></packing></child><child><object class=\"GtkAlignment\" id=\"align"
  "ment7\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"xalign\">0</property><property"
  " name=\"xscale\">0</property><property name=\"yscale\">0</property><chi"
  "ld><object class=\"GtkButton\" id=\"device-reset-feedback\"><property n"
  "ame=\"label\" translatable=\"yes\">_Reset to Defaults</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Set the acceleration and sensitivity for the"
  " selected device to the default values</property><property name=\"image"
  "\">image5</property><property name=\"use_underline\">True</property></o"
  "bject></child></object><packing><property name=\"right_attach\">2</prop"
  "erty><property name=\"top_attach\">2</property><property name=\"bottom_"
  "attach\">3</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label15\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">Pointer Speed<"
  "/property><attributes><attribute name=\"weight\" value=\"bold\"/></attr"
  "ibutes></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child><child type=\"t"
  "ab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">B_uttons and Feedback</property><pr"
  "operty name=\"use_underline\">True</property></object><packing><propert"
  "y name=\"tab_fill\">False</property></packing></child><child><object cl"
  "ass=\"GtkVBox\" id=\"synaptics-tab\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"b"
  "order_width\">6</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkFrame\" id=\"frame11\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label_xalign\">0</property><property name=\"shadow_type\">none</pr"
  "operty><child><object class=\"GtkAlignment\" id=\"alignment13\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkVBox\" id=\"vbox11\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"border_w"
  "idth\">6</property><property name=\"spacing\">6</property><child><objec"
  "t class=\"GtkCheckButton\" id=\"synaptics-tap-to-click\"><property name"
  "=\"label\" translatable=\"yes\">Tap touchpad to clic_k</property><prope"
  "rty name=\"use_action_appearance\">False</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"receives_default\">False</property><property name=\"use_und"
  "erline\">True</property><property name=\"draw_indicator\">True</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">2</property></"
  "packing></child></object></child></object></child><child type=\"label\""
  "><object class=\"GtkLabel\" id=\"label16\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label\" translatable=\"yes\">General</property><property name=\"us"
  "e_markup\">True</property><attributes><attribute name=\"weight\" value="
  "\"bold\"/></attributes></object></child></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">0</property></packing></child></object><packin"
  "g><property name=\"position\">1</property></packing></child><child type"
  "=\"tab\"><object class=\"GtkLabel\" id=\"synaptics-label\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">T_ouchpad</property><"
  "property name=\"use_underline\">True</property></object><packing><prope"
  "rty name=\"position\">1</property><property name=\"tab_fill\">False</pr"
  "operty></packing></child><child><object class=\"GtkVBox\" id=\"wacom-ta"
  "b\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"border_width\">6</property><proper"
  "ty name=\"spacing\">6</property><child><object class=\"GtkFrame\" id=\""
  "frame12\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label_xalign\">0</property><"
  "property name=\"shadow_type\">none</property><child><object class=\"Gtk"
  "Alignment\" id=\"alignment14\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"left_pa"
  "dding\">12</property><child><object class=\"GtkTable\" id=\"table2\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"border_width\">6</property><property nam"
  "e=\"n_rows\">2</property><property name=\"n_columns\">2</property><prop"
  "erty name=\"column_spacing\">12</property><property name=\"row_spacing\""
  ">6</property><child><object class=\"GtkLabel\" id=\"label9\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"xalign\">0</property><property name=\"label\" tr"
  "anslatable=\"yes\">Trac_king mode:</property><property name=\"use_under"
  "line\">True</property><property name=\"mnemonic_widget\">wacom-mode</pr"
  "operty></object><packing><property name=\"x_options\">GTK_FILL</propert"
  "y></packing></child><child><object class=\"GtkLabel\" id=\"label10\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"xalign\">0</property><property name=\"la"
  "bel\" translatable=\"yes\">_Rotation:</property><property name=\"use_un"
  "derline\">True</property><property name=\"mnemonic_widget\">wacom-rotat"
  "ion</property></object><packing><property name=\"top_attach\">1</proper"
  "ty><property name=\"bottom_attach\">2</property><property name=\"x_opti"
  "ons\">GTK_FILL</property></packing></child><child><object class=\"GtkCo"
  "mboBox\" id=\"wacom-mode\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"model\">wac"
  "om-mode-store</property><child><object class=\"GtkCellRendererText\" id"
  "=\"cellrenderertext1\"/><attributes><attribute name=\"text\">1</attribu"
  "te></attributes></child></object><packing><property name=\"left_attach\""
  ">1</property><property name=\"right_attach\">2</property></packing></ch"
  "ild><child><object class=\"GtkComboBox\" id=\"wacom-rotation\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"model\">wacom-rotation-store</property><child>"
  "<object class=\"GtkCellRendererText\" id=\"cellrenderertext2\"/><attrib"
  "utes><attribute name=\"text\">1</attribute></attributes></child></objec"
  "t><packing><property name=\"left_attach\">1</property><property name=\""
  "right_attach\">2</property><property name=\"top_attach\">1</property><p"
  "roperty name=\"bottom_attach\">2</property></packing></child></object><"
  "/child></object></child><child type=\"label\"><object class=\"GtkLabel\""
  " id=\"label18\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">General</property><property name=\"use_markup\">True</property><a"
  "ttributes><attribute name=\"weight\" value=\"bold\"/></attributes></obj"
  "ect></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child></object><packing><property name=\"position\""
  ">2</property></packing></child><child type=\"tab\"><object class=\"GtkL"
  "abel\" id=\"wacom-label\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">Tab_let</property><property name=\"use_underline\">Tru"
  "e</property></object><packing><property name=\"position\">2</property><"
  "property name=\"tab_fill\">False</property></packing></child></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">2</property></packing></chi"
  "ld></object></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Devices</property><property name=\"use_underline\">True</property></ob"
  "ject><packing><property name=\"tab_fill\">False</property></packing></c"
  "hild><child><object class=\"GtkVBox\" id=\"vbox3\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"border_width\">12</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkFrame\" id=\"frame3\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label_xalign\">0</property><property name=\"shadow_t"
  "ype\">none</property><child><object class=\"GtkAlignment\" id=\"alignme"
  "nt3\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"left_padding\">12</property><chi"
  "ld><object class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkLabel\" id=\"mouse-dnd-label\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"xalign\">0</property><property name=\"label\" transla"
  "table=\"yes\">Th_reshold:</property><property name=\"use_underline\">Tr"
  "ue</property><property name=\"mnemonic_widget\">dnd-threshold-scale</pr"
  "operty></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkHScale\" id=\"dnd-thresh"
  "old-scale\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">The number of pixels the pointer must move before a drag opera"
  "tion will start</property><property name=\"update_policy\">delayed</pro"
  "perty><property name=\"adjustment\">dnd-threshold</property><property n"
  "ame=\"digits\">0</property><property name=\"value_pos\">right</property"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">1</property></p"
  "acking></child></object></child></object></child><child type=\"label\">"
  "<object class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label\" translatable=\"yes\">Drag and Drop</property><attributes><at"
  "tribute name=\"weight\" value=\"bold\"/></attributes></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkFrame\" id=\"frame4\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label_xalign\">0</property><property name=\"sha"
  "dow_type\">none</property><child><object class=\"GtkAlignment\" id=\"al"
  "ignment4\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"left_padding\">12</property"
  "><child><object class=\"GtkVBox\" id=\"vbox5\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">6</property><property name=\"spacing\">6</prope"
  "rty><child><object class=\"GtkLabel\" id=\"dclick-time-label\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"xalign\">0</property><property name=\"label\" "
  "translatable=\"yes\">Ti_me:</property><property name=\"use_underline\">"
  "True</property><property name=\"mnemonic_widget\">dclick-time-scale</pr"
  "operty></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkHScale\" id=\"dclick-tim"
  "e-scale\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"tooltip_text\" translatable=\""
  "yes\">Two mouse clicks in less than this length of time (in millisecond"
  "s) will be considered a double click</property><property name=\"update_"
  "policy\">delayed</property><property name=\"adjustment\">dclick-time</p"
  "roperty><property name=\"digits\">0</property><property name=\"value_po"
  "s\">right</property></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">1</property></packing></child><child><object class=\"GtkLabel\" id="
  "\"dclick-distance-label\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"xalign\">0</"
  "property><property name=\"label\" translatable=\"yes\">D_istance:</prop"
  "erty><property name=\"use_underline\">True</property><property name=\"m"
  "nemonic_widget\">dclick-distance-scale</property></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">2</property></packing></child><child><"
  "object class=\"GtkHScale\" id=\"dclick-distance-scale\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"tooltip_text\" translatable=\"yes\">The mouse pointer "
  "cannot move farther than this distance between two clicks for them to b"
  "e considered a double click</property><property name=\"update_policy\">"
  "delayed</property><property name=\"adjustment\">dclick-distance</proper"
  "ty><property name=\"digits\">0</property><property name=\"value_pos\">r"
  "ight</property></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">3"
  "</property></packing></child></object></child></object></child><child t"
  "ype=\"label\"><object class=\"GtkLabel\" id=\"label8\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">Double Click</property><at"
  "tributes><attribute name=\"weight\" value=\"bold\"/></attributes></obje"
  "ct></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">1</p"
  "roperty></packing></child></object><packing><property name=\"position\""
  ">1</property></packing></child><child type=\"tab\"><object class=\"GtkL"
  "abel\" id=\"label2\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label\" translata"
  "ble=\"yes\">_Behavior</property><property name=\"use_underline\">True</"
  "property></object><packing><property name=\"position\">1</property><pro"
  "perty name=\"tab_fill\">False</property></packing></child><child><objec"
  "t class=\"GtkHBox\" id=\"themes-hbox\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">12</property><property name=\"spacing\">12</property><ch"
  "ild><object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"hscrollbar_policy\">automatic</property><proper"
  "ty name=\"vscrollbar_policy\">automatic</property><property name=\"shad"
  "ow_type\">etched-in</property><child><object class=\"GtkTreeView\" id=\""
  "theme-treeview\"><property name=\"width_request\">200</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"headers_visible\">False</property></object></c"
  "hild></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">0</property"
  "></packing></child><child><object class=\"GtkVBox\" id=\"vbox9\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"spacing\">6</property><child><object class=\""
  "GtkFrame\" id=\"frame5\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label_xalign\""
  ">0</property><property name=\"shadow_type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment5\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"left_padding\">12</property><child><object class=\"GtkHBox\" id=\""
  "hbox7\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">6</property><pr"
  "operty name=\"spacing\">12</property><child><object class=\"GtkLabel\" "
  "id=\"label21\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Cursor si_ze:</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"mnemonic_widget\">spin1</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "True</property><property name=\"position\">0</property></packing></chil"
  "d><child><object class=\"GtkSpinButton\" id=\"spin1\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"primary_icon_activatable\">False</property><property nam"
  "e=\"secondary_icon_activatable\">False</property><property name=\"prima"
  "ry_icon_sensitive\">True</property><property name=\"secondary_icon_sens"
  "itive\">True</property><property name=\"adjustment\">theme-cursor-size<"
  "/property><property name=\"snap_to_ticks\">True</property><property nam"
  "e=\"numeric\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child></object></child></object></"
  "child><child type=\"label\"><object class=\"GtkLabel\" id=\"label20\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">Size</prop"
  "erty><attributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkFrame\" id="
  "\"frame6\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"label_xalign\">0</property>"
  "<property name=\"shadow_type\">none</property><child><object class=\"Gt"
  "kAlignment\" id=\"alignment6\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">6</property><property name=\"xalign\">0</property><property nam"
  "e=\"yalign\">0</property><property name=\"xscale\">0</property><propert"
  "y name=\"yscale\">0</property><property name=\"top_padding\">6</propert"
  "y><property name=\"bottom_padding\">6</property><property name=\"left_p"
  "adding\">18</property><property name=\"right_padding\">6</property><chi"
  "ld><object class=\"GtkImage\" id=\"theme-preview\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"stock\">gtk-missing-image</property></object></child></obj"
  "ect></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label"
  "22\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"label\" translatable=\"yes\">Prev"
  "iew</property><attributes><attribute name=\"weight\" value=\"bold\"/></"
  "attributes></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">1</property></packing></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child></object><pac"
  "king><property name=\"position\">2</property></packing></child><child t"
  "ype=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label\" translatable=\"yes\">_Theme</property><property "
  "name=\"use_underline\">True</property></object><packing><property name="
  "\"position\">2</property><property name=\"tab_fill\">False</property></"
  "packing></child></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child></object></child><action-widgets><action-"
  "widget response=\"0\">button1</action-widget><action-widget response=\""
  "-11\">button2</action-widget></action-widgets></object><object class=\""
  "GtkListStore\" id=\"wacom-mode-store\"><columns><column type=\"gchararr"
  "ay\"/><column type=\"gchararray\"/></columns><data><row><col id=\"0\">A"
  "BSOLUTE</col><col id=\"1\" translatable=\"yes\">Pen (absolute)</col></r"
  "ow><row><col id=\"0\">RELATIVE</col><col id=\"1\" translatable=\"yes\">"
  "Mouse (relative)</col></row></data></object></interface>"
};

static const unsigned mouse_dialog_ui_length = 34088u;

