/* automatically generated from mouse-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (mouse_dialog_ui)
#endif
#ifdef __GNUC__
static const char mouse_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char mouse_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.20\"/><object class=\"GtkAdjustment\" id=\"dclick-dist"
  "ance\"><property name=\"upper\">20</property><property name=\"value\">4"
  "</property><property name=\"step_increment\">1</property><property name"
  "=\"page_increment\">5</property></object><object class=\"GtkAdjustment\""
  " id=\"dclick-time\"><property name=\"lower\">100</property><property na"
  "me=\"upper\">2000</property><property name=\"value\">250</property><pro"
  "perty name=\"step_increment\">1</property><property name=\"page_increme"
  "nt\">100</property></object><object class=\"GtkAdjustment\" id=\"device"
  "-acceleration\"><property name=\"upper\">10</property><property name=\""
  "value\">2</property><property name=\"step_increment\">0.100000000000000"
  "01</property><property name=\"page_increment\">1</property></object><ob"
  "ject class=\"GtkAdjustment\" id=\"device-threshold\"><property name=\"l"
  "ower\">1</property><property name=\"upper\">5</property><property name="
  "\"value\">4</property><property name=\"step_increment\">1</property><pr"
  "operty name=\"page_increment\">1</property></object><object class=\"Gtk"
  "Adjustment\" id=\"dnd-threshold\"><property name=\"lower\">1</property>"
  "<property name=\"upper\">50</property><property name=\"value\">8</prope"
  "rty><property name=\"step_increment\">1</property><property name=\"page"
  "_increment\">10</property></object><object class=\"GtkImage\" id=\"imag"
  "e5\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"stock\">gtk-revert-to-saved</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"synaptics-disable-du"
  "ration\"><property name=\"lower\">0.10000000000000001</property><proper"
  "ty name=\"upper\">4</property><property name=\"value\">2</property><pro"
  "perty name=\"step_increment\">0.10000000000000001</property><property n"
  "ame=\"page_increment\">1</property></object><object class=\"GtkListStor"
  "e\" id=\"synaptics-scroll-store\"><columns><column type=\"gchararray\"/"
  "><column type=\"gboolean\"/></columns><data><row><col id=\"0\" translat"
  "able=\"yes\">Disabled</col><col id=\"1\">True</col></row><row><col id=\""
  "0\" translatable=\"yes\">Edge scrolling</col><col id=\"1\">True</col></"
  "row><row><col id=\"0\" translatable=\"yes\">Two-finger scrolling</col><"
  "col id=\"1\">True</col></row><row><col id=\"0\" translatable=\"yes\">Ci"
  "rcular scrolling</col><col id=\"1\">True</col></row></data></object><ob"
  "ject class=\"GtkAdjustment\" id=\"theme-cursor-size\"><property name=\""
  "lower\">16</property><property name=\"upper\">48</property><property na"
  "me=\"value\">24</property><property name=\"step_increment\">1</property"
  "><property name=\"page_increment\">11</property></object><object class="
  "\"GtkListStore\" id=\"wacom-mode-store\"><columns><column type=\"gchara"
  "rray\"/><column type=\"gchararray\"/></columns><data><row><col id=\"0\""
  ">ABSOLUTE</col><col id=\"1\" translatable=\"yes\">Pen (absolute)</col><"
  "/row><row><col id=\"0\">RELATIVE</col><col id=\"1\" translatable=\"yes\""
  ">Mouse (relative)</col></row></data></object><object class=\"GtkListSto"
  "re\" id=\"wacom-rotation-store\"><columns><column type=\"gint\"/><colum"
  "n type=\"gchararray\"/></columns><data><row><col id=\"0\">0</col><col i"
  "d=\"1\" translatable=\"yes\">None (right-handed)</col></row><row><col i"
  "d=\"0\">3</col><col id=\"1\" translatable=\"yes\">Half (left-handed)</c"
  "ol></row><row><col id=\"0\">1</col><col id=\"1\" translatable=\"yes\">C"
  "lockwise</col></row><row><col id=\"0\">2</col><col id=\"1\" translatabl"
  "e=\"yes\">Counterclockwise</col></row></data></object><object class=\"X"
  "fceTitledDialog\" id=\"mouse-dialog\"><property name=\"can_focus\">Fals"
  "e</property><property name=\"title\" translatable=\"yes\">Mouse and Tou"
  "chpad</property><property name=\"window_position\">center-on-parent</pr"
  "operty><property name=\"icon_name\">preferences-desktop-peripherals</pr"
  "operty><property name=\"type_hint\">dialog</property><property name=\"s"
  "ubtitle\" translatable=\"yes\">Configure pointer device behavior and ap"
  "pearance</property><child internal-child=\"vbox\"><object class=\"GtkVB"
  "ox\" id=\"dialog-vbox1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"spacing\">2</"
  "property><child internal-child=\"action_area\"><object class=\"GtkHButt"
  "onBox\" id=\"dialog-action_area1\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lay"
  "out_style\">end</property><child><object class=\"GtkButton\" id=\"butto"
  "n2\"><property name=\"label\">gtk-help</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">True</property><property name=\"use_stock\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property><property name=\"secondary\">True</property></packing></ch"
  "ild><child><object class=\"GtkButton\" id=\"button1\"><property name=\""
  "label\">gtk-close</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">True</property><property name=\"use_stock\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">0</property></pack"
  "ing></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"pack_type\">en"
  "d</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkNotebook\" id=\"plug-child\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"border_width\">6</property><child><object class=\"GtkVBo"
  "x\" id=\"vbox1\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"border_width\">12</pr"
  "operty><property name=\"spacing\">6</property><child><object class=\"Gt"
  "kHBox\" id=\"hbox1\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"spacing\">12</pro"
  "perty><child><object class=\"GtkLabel\" id=\"label7\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">De_vice:</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"mnemonic_widg"
  "et\">device-combobox</property><property name=\"angle\">0.0500000000000"
  "00003</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkComboBox\" id="
  "\"device-combobox\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">1</property></packing></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><object class=\"GtkCheckButton\" id=\"device-enabled\"><property name="
  "\"label\" translatable=\"yes\">_Enable this device</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">False</property><property name"
  "=\"use_underline\">True</property><property name=\"draw_indicator\">Tru"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child><child><object class=\"GtkNotebook\" id=\"de"
  "vice-notebook\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><child><object class=\"GtkVBox\" id=\"de"
  "vice-box\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"border_width\">6</property>"
  "<property name=\"spacing\">6</property><child><object class=\"GtkFrame\""
  " id=\"frame1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label_xalign\">0</prope"
  "rty><property name=\"shadow_type\">none</property><child><object class="
  "\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkVBox\" id=\"vbox12\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkHBox\" id=\"hbox"
  "3\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"spacing\">12</property><child><obj"
  "ect class=\"GtkRadioButton\" id=\"device-right-handed\"><property name="
  "\"label\" translatable=\"yes\">Ri_ght-handed</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"active\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkRadioButton\" id=\"device-left-handed\"><property name="
  "\"label\" translatable=\"yes\">Le_ft-handed</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty><property name=\"group\">device-right-handed</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"device-re"
  "verse-scrolling\"><property name=\"label\" translatable=\"yes\">Reverse"
  " scroll d_irection</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"tooltip_text\" translatable=\""
  "yes\">When selected, the scroll wheel will work in the opposite directi"
  "on</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object></child><"
  "/object></child><child type=\"label\"><object class=\"GtkLabel\" id=\"l"
  "abel14\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "Buttons</property><attributes><attribute name=\"weight\" value=\"bold\""
  "/></attributes></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkFrame\" id=\"frame2\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label_xalign\""
  ">0</property><property name=\"shadow_type\">none</property><child><obje"
  "ct class=\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"left_padding\">12</property><child><object class=\"GtkTable\" id="
  "\"table1\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"border_width\">6</property>"
  "<property name=\"n_rows\">2</property><property name=\"n_columns\">2</p"
  "roperty><property name=\"column_spacing\">12</property><property name=\""
  "row_spacing\">6</property><child><object class=\"GtkHScale\" id=\"devic"
  "e-threshold-scale\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"tooltip_text\" tran"
  "slatable=\"yes\">The number of pixels the pointer must move in a short "
  "time before it starts accelerating</property><property name=\"update_po"
  "licy\">delayed</property><property name=\"adjustment\">device-threshold"
  "</property><property name=\"round_digits\">0</property><property name=\""
  "digits\">0</property><property name=\"value_pos\">right</property></obj"
  "ect><packing><property name=\"left_attach\">1</property><property name="
  "\"right_attach\">2</property></packing></child><child><object class=\"G"
  "tkLabel\" id=\"device-threshold-label\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"xalign\">0</property><property name=\"label\" translatable=\"yes\">Se"
  "nsitivit_y:</property><property name=\"use_underline\">True</property><"
  "property name=\"mnemonic_widget\">device-threshold-scale</property></ob"
  "ject><packing><property name=\"x_options\">GTK_FILL</property></packing"
  "></child><child><object class=\"GtkAlignment\" id=\"alignment7\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"xalign\">0</property><property name=\"xscale"
  "\">0</property><property name=\"yscale\">0</property><child><object cla"
  "ss=\"GtkButton\" id=\"device-reset-feedback\"><property name=\"label\" "
  "translatable=\"yes\">_Reset to Defaults</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">True</property><property name=\"tooltip_t"
  "ext\" translatable=\"yes\">Set the acceleration and sensitivity for the"
  " selected device to the default values</property><property name=\"image"
  "\">image5</property><property name=\"use_underline\">True</property></o"
  "bject></child></object><packing><property name=\"right_attach\">2</prop"
  "erty><property name=\"top_attach\">1</property><property name=\"bottom_"
  "attach\">2</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label15\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">Pointer Speed<"
  "/property><attributes><attribute name=\"weight\" value=\"bold\"/></attr"
  "ibutes></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child><child type=\"t"
  "ab\"><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">B_uttons and Feedback</property><pr"
  "operty name=\"use_underline\">True</property></object><packing><propert"
  "y name=\"tab_fill\">False</property></packing></child><child><object cl"
  "ass=\"GtkVBox\" id=\"synaptics-tab\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"b"
  "order_width\">6</property><property name=\"spacing\">6</property><child"
  "><object class=\"GtkFrame\" id=\"frame11\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"label_xalign\">0</property><property name=\"shadow_type\">none</pr"
  "operty><child><object class=\"GtkAlignment\" id=\"alignment13\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"left_padding\">12</property><child><object cl"
  "ass=\"GtkVBox\" id=\"vbox11\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"border_w"
  "idth\">6</property><property name=\"spacing\">6</property><child><objec"
  "t class=\"GtkCheckButton\" id=\"synaptics-tap-to-click\"><property name"
  "=\"label\" translatable=\"yes\">Tap touchpad to clic_k</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object></child></object></child></object></child><chi"
  "ld type=\"label\"><object class=\"GtkLabel\" id=\"label16\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">General</property><p"
  "roperty name=\"use_markup\">True</property><attributes><attribute name="
  "\"weight\" value=\"bold\"/></attributes></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkFrame\" id=\"frame10\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label_xalign\">0</property><property name=\"shadow_type\">n"
  "one</property><child><object class=\"GtkAlignment\" id=\"alignment12\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"left_padding\">12</property><child><pl"
  "aceholder/></child></object></child><child type=\"label_item\"><placeho"
  "lder/></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">1"
  "</property></packing></child></object><packing><property name=\"positio"
  "n\">1</property></packing></child><child type=\"tab\"><object class=\"G"
  "tkLabel\" id=\"synaptics-label\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">T_ouchpad</property><property name=\"use_underl"
  "ine\">True</property></object><packing><property name=\"position\">1</p"
  "roperty><property name=\"tab_fill\">False</property></packing></child><"
  "child><object class=\"GtkVBox\" id=\"wacom-tab\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"border_width\">6</property><property name=\"spacing\">6</pro"
  "perty><child><object class=\"GtkFrame\" id=\"frame12\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label_xalign\">0</property><property name=\"shadow_type"
  "\">none</property><child><object class=\"GtkAlignment\" id=\"alignment1"
  "4\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"left_padding\">12</property><child"
  "><object class=\"GtkTable\" id=\"table2\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"border_width\">6</property><property name=\"n_rows\">2</property><p"
  "roperty name=\"n_columns\">2</property><property name=\"column_spacing\""
  ">12</property><property name=\"row_spacing\">6</property><child><object"
  " class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"xali"
  "gn\">0</property><property name=\"label\" translatable=\"yes\">Trac_kin"
  "g mode:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">wacom-mode</property></object><packing><p"
  "roperty name=\"x_options\">GTK_FILL</property></packing></child><child>"
  "<object class=\"GtkLabel\" id=\"label10\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"xalign\">0</property><property name=\"label\" translatable=\"yes\">"
  "_Rotation:</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"mnemonic_widget\">wacom-rotation</property></object><pac"
  "king><property name=\"top_attach\">1</property><property name=\"bottom_"
  "attach\">2</property><property name=\"x_options\">GTK_FILL</property></"
  "packing></child><child><object class=\"GtkComboBox\" id=\"wacom-mode\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"model\">wacom-mode-store</property><ch"
  "ild><object class=\"GtkCellRendererText\" id=\"cellrenderertext1\"/><at"
  "tributes><attribute name=\"text\">1</attribute></attributes></child></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"right_attach\">2</property></packing></child><child><object class=\""
  "GtkComboBox\" id=\"wacom-rotation\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"mo"
  "del\">wacom-rotation-store</property><child><object class=\"GtkCellRend"
  "ererText\" id=\"cellrenderertext2\"/><attributes><attribute name=\"text"
  "\">1</attribute></attributes></child></object><packing><property name=\""
  "left_attach\">1</property><property name=\"right_attach\">2</property><"
  "property name=\"top_attach\">1</property><property name=\"bottom_attach"
  "\">2</property></packing></child></object></child></object></child><chi"
  "ld type=\"label\"><object class=\"GtkLabel\" id=\"label18\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">General</property><p"
  "roperty name=\"use_markup\">True</property><attributes><attribute name="
  "\"weight\" value=\"bold\"/></attributes></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "></object><packing><property name=\"position\">2</property></packing></"
  "child><child type=\"tab\"><object class=\"GtkLabel\" id=\"wacom-label\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Tab_let<"
  "/property><property name=\"use_underline\">True</property></object><pac"
  "king><property name=\"position\">2</property><property name=\"tab_fill\""
  ">False</property></packing></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">2</property></packing></child></object></child><chil"
  "d type=\"tab\"><object class=\"GtkLabel\" id=\"label1\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">_Devices</property><prop"
  "erty name=\"use_underline\">True</property></object><packing><property "
  "name=\"tab_fill\">False</property></packing></child><child><object clas"
  "s=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"border_widt"
  "h\">12</property><property name=\"spacing\">6</property><child><object "
  "class=\"GtkFrame\" id=\"frame3\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "_xalign\">0</property><property name=\"shadow_type\">none</property><ch"
  "ild><object class=\"GtkAlignment\" id=\"alignment3\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"left_padding\">12</property><child><object class=\"GtkVB"
  "ox\" id=\"vbox4\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"border_width\">6</pr"
  "operty><property name=\"spacing\">6</property><child><object class=\"Gt"
  "kLabel\" id=\"mouse-dnd-label\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"xalign"
  "\">0</property><property name=\"label\" translatable=\"yes\">Th_reshold"
  ":</property><property name=\"use_underline\">True</property><property n"
  "ame=\"mnemonic_widget\">dnd-threshold-scale</property></object><packing"
  "><property name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkHScale\" id=\"dnd-threshold-scale\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"tooltip_text\" translatable=\"yes\">The number of p"
  "ixels the pointer must move before a drag operation will start</propert"
  "y><property name=\"update_policy\">delayed</property><property name=\"a"
  "djustment\">dnd-threshold</property><property name=\"digits\">0</proper"
  "ty><property name=\"value_pos\">right</property></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "</child></object></child><child type=\"label\"><object class=\"GtkLabel"
  "\" id=\"label6\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">Drag and Drop</property><attributes><attribute name=\"weight\" "
  "value=\"bold\"/></attributes></object></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkFrame\" id=\"frame4\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment4\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkVBox\" id=\"vbox5\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"border_width\">"
  "6</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkLabel\" id=\"dclick-time-label\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "xalign\">0</property><property name=\"label\" translatable=\"yes\">Ti_m"
  "e:</property><property name=\"use_underline\">True</property><property "
  "name=\"mnemonic_widget\">dclick-time-scale</property></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkHScale\" id=\"dclick-time-scale\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"tooltip_text\" translatable=\"yes\">Two mouse clicks i"
  "n less than this length of time (in milliseconds) will be considered a "
  "double click</property><property name=\"update_policy\">delayed</proper"
  "ty><property name=\"adjustment\">dclick-time</property><property name=\""
  "digits\">0</property><property name=\"value_pos\">right</property></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"dclick-distance-label\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"xalign\">0</property><property name=\""
  "label\" translatable=\"yes\">D_istance:</property><property name=\"use_"
  "underline\">True</property><property name=\"mnemonic_widget\">dclick-di"
  "stance-scale</property></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">2</property></packing></child><child><object class=\"GtkHScale\""
  " id=\"dclick-distance-scale\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"tooltip_t"
  "ext\" translatable=\"yes\">The mouse pointer cannot move farther than t"
  "his distance between two clicks for them to be considered a double clic"
  "k</property><property name=\"update_policy\">delayed</property><propert"
  "y name=\"adjustment\">dclick-distance</property><property name=\"digits"
  "\">0</property><property name=\"value_pos\">right</property></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">3</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><object clas"
  "s=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"label\" t"
  "ranslatable=\"yes\">Double Click</property><attributes><attribute name="
  "\"weight\" value=\"bold\"/></attributes></object></child></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"position\">1</property></packing></"
  "child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">_Behavior</pr"
  "operty><property name=\"use_underline\">True</property></object><packin"
  "g><property name=\"position\">1</property><property name=\"tab_fill\">F"
  "alse</property></packing></child><child><object class=\"GtkHBox\" id=\""
  "themes-hbox\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"border_width\">12</prope"
  "rty><property name=\"spacing\">12</property><child><object class=\"GtkS"
  "crolledWindow\" id=\"scrolledwindow2\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "hscrollbar_policy\">automatic</property><property name=\"vscrollbar_pol"
  "icy\">automatic</property><property name=\"shadow_type\">etched-in</pro"
  "perty><child><object class=\"GtkTreeView\" id=\"theme-treeview\"><prope"
  "rty name=\"width_request\">200</property><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">True</property><property name="
  "\"headers_visible\">False</property></object></child></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkVBox\" id=\"vbox9\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"spacing\">6</property><child><object class=\"GtkFrame\" id=\"frame5"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label_xalign\">0</property><propert"
  "y name=\"shadow_type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment5\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"left_padding\">"
  "12</property><child><object class=\"GtkHBox\" id=\"hbox7\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"border_width\">6</property><property name=\"spacin"
  "g\">12</property><child><object class=\"GtkLabel\" id=\"label21\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">Cursor si_ze:<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"mnemonic_widget\">spin1</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">0</property></packing></child><child><object cla"
  "ss=\"GtkSpinButton\" id=\"spin1\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"prima"
  "ry_icon_activatable\">False</property><property name=\"secondary_icon_a"
  "ctivatable\">False</property><property name=\"primary_icon_sensitive\">"
  "True</property><property name=\"secondary_icon_sensitive\">True</proper"
  "ty><property name=\"adjustment\">theme-cursor-size</property><property "
  "name=\"snap_to_ticks\">True</property><property name=\"numeric\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\">1</pro"
  "perty></packing></child></object></child></object></child><child type=\""
  "label\"><object class=\"GtkLabel\" id=\"label20\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">Size</property><attributes><at"
  "tribute name=\"weight\" value=\"bold\"/></attributes></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkFrame\" id=\"frame6\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label_xalign\">0</property><property name=\"sha"
  "dow_type\">none</property><child><object class=\"GtkAlignment\" id=\"al"
  "ignment6\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"border_width\">6</property>"
  "<property name=\"xalign\">0</property><property name=\"yalign\">0</prop"
  "erty><property name=\"xscale\">0</property><property name=\"yscale\">0<"
  "/property><property name=\"top_padding\">6</property><property name=\"b"
  "ottom_padding\">6</property><property name=\"left_padding\">18</propert"
  "y><property name=\"right_padding\">6</property><child><object class=\"G"
  "tkImage\" id=\"theme-preview\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"stock\""
  ">gtk-missing-image</property></object></child></object></child><child t"
  "ype=\"label\"><object class=\"GtkLabel\" id=\"label22\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"label\" translatable=\"yes\">Preview</property><attri"
  "butes><attribute name=\"weight\" value=\"bold\"/></attributes></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">1</prop"
  "erty></packing></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">1</property></packing></child></object><packing><property name="
  "\"position\">2</property></packing></child><child type=\"tab\"><object "
  "class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">_Theme</property><property name=\"use_underline"
  "\">True</property></object><packing><property name=\"position\">2</prop"
  "erty><property name=\"tab_fill\">False</property></packing></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object></child><action-widgets><action-widget response=\"-11"
  "\">button2</action-widget><action-widget response=\"0\">button1</action"
  "-widget></action-widgets></object></interface>"
};

static const unsigned mouse_dialog_ui_length = 32914u;

