.TH XFCE4-APPEARANCE-SETTINGS "1" "September 2013" "xfce4-appearance-settings 4.11.0 (Xfce 4.10)" "User Commands"
.SH NAME
xfce4-appearance-settings \- Appearance settings for Xfce
.SH DESCRIPTION
.SS "Usage:"
.IP
xfce4\-appearance\-settings [OPTION...]
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.PP
GTK+ Options
.TP
\fB\-\-class\fR=\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-name\fR=\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-screen\fR=\fISCREEN\fR
X screen to use
.TP
\fB\-\-sync\fR
Make X calls synchronous
.TP
\fB\-\-gtk\-module\fR=\fIMODULES\fR
Load additional GTK+ modules
.TP
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal
.SS "Application Options:"
.TP
\fB\-s\fR, \fB\-\-socket\-id\fR=\fISOCKET\fR ID
Settings manager socket
.TP
\fB\-v\fR, \fB\-\-version\fR
Version information
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH COPYRIGHT
Copyright \(co 2008\-2011
.IP
The Xfce development team. All rights reserved.
.PP
Please report bugs to <http://bugzilla.xfce.org/>.
