.TH XFSETTINGSD "1" "September 2013" "xfsettingsd 4.11.0 (Xfce 4.10)" "User Commands"
.SH NAME
xfsettingsd \- XSettings daemon for Xfce
.SH DESCRIPTION
.SS "Usage:"
.IP
xfsettingsd [OPTION...]
.SS "Help Options:"
.TP
\fB\-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB\-\-help\-all\fR
Show all help options
.TP
\fB\-\-help\-gtk\fR
Show GTK+ Options
.TP
\fB\-\-help\-sm\-client\fR
Show session management options
.PP
GTK+ Options
.TP
\fB\-\-class\fR=\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-name\fR=\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-screen\fR=\fISCREEN\fR
X screen to use
.TP
\fB\-\-sync\fR
Make X calls synchronous
.TP
\fB\-\-gtk\-module\fR=\fIMODULES\fR
Load additional GTK+ modules
.TP
\fB\-\-g\-fatal\-warnings\fR
Make all warnings fatal
.PP
Session management options
.TP
\fB\-\-sm\-client\-id\fR=\fIID\fR
Session management client ID
.TP
\fB\-\-sm\-client\-disable\fR
Disable session management
.SS "Application Options:"
.TP
\fB\-V\fR, \fB\-\-version\fR
Version information
.TP
\fB\-\-no\-daemon\fR
Do not fork to the background
.TP
\fB\-\-replace\fR
Replace running xsettings daemon (if any)
.TP
\fB\-\-display\fR=\fIDISPLAY\fR
X display to use
.SH COPYRIGHT
Copyright \(co 2008\-2011
.IP
The Xfce development team. All rights reserved.
.PP
Please report bugs to <http://bugzilla.xfce.org/>.
